### ISSUE TITLE
How to decompile code.pbin?

### ISSUE THREAD

**Issue by rustov** [SteamDatabase/ValveResourceFormat#106]
Hello. How to decompile code.pbin?

**Comment by psychonic** [comment]
Easily.

**Comment by SinZ163** [comment]
Rename it to .zip and you will figure it out from there

**Comment by rustov** [comment]
Yes, but how to change something in this file?

**Comment by rustov** [comment]
After any change the game gives an error:
https://i.imgur.com/AA1RRb0.png
