### ISSUE TITLE
Audio type 0 is not necessarily AAC

### ISSUE THREAD

**Issue by ProdigySim** [SteamDatabase/ValveResourceFormat#117]
I just found this tool and tried it out for extracting Artifact sounds. It looks like you recently added support for `audioType = 0` which was necessary for Artifact `.vsnd_c` files.

Looking at one of the Artifact sound files in `pak01_dir.vpk`, `sound/responses/set_01/centaur_warrunner/centaur_warrunner_angry_05.vsnd_c` with VRV GUI:
```
{
	uint32 m_bitpackedsoundinfo = 0x0202AC44
	int32 m_loopStart = -1
	float32 m_flDuration = 2.645125
}

Sample Rate: 2058
Bits: 17
Type: AAC
SampleSize: 6
Format: 2
Channels: 0
```

I assume the `0` at the start of `m_bitpackedsoundinfo` means audio type 0. The VRV viewer plays it just fine, but if I extract it to play it myself it looks like an MP3 rather than an AAC:

At offset 0x2F0 into the file this looks like the header of the actual file:
![image](https://user-images.githubusercontent.com/857937/49399033-bfd36700-f705-11e8-89b3-9cab1a1e0214.png)

You can see "LAME 3.100" near the end of the header; suggesting LAME MP3.

If I clip the file to the screenshotted offset and load it into my favorite audio player, it shows that it's a VBR mp3:
![image](https://user-images.githubusercontent.com/857937/49399084-eabdbb00-f705-11e8-8993-82d84978854a.png)

Maybe just a minor nit, since operationally the tool seems to work. Thought I'd add this info.

**Comment by xPaw** [comment]
It indeed doesn't matter for the extractor because it doesn't do anything with it.

And AAC was the best guess I made at the time because we have no info how Valve names it (iirc resourceinfo doesn't say anything about it either, but maybe that changed?).

**Comment by xPaw** [comment]
new sounds in the battlepass `pak01_dir/sounds/misc/soundboard` are being detected as AAC but also appear to be mp3.

I'm not sure how we can fix this properly. @SinZ163?

**Comment by mdiller** [comment]
so as far as I can tell, it looks like all the new sounds in `pak01_dir/sounds/misc/soundboard` are wav files without a header that are being identified as audio type 0. I confirmed this by taking the output of the decompiler and ran this bit of python on it, which created what seems to be the correct audio:
```py
import struct
import wave

with wave.open("ti9_kooka_laugh_fixed.wav", "wb") as wavef:
	with open("ti9_kooka_laugh.wav", "rb") as f:
		data = f.read()
		wavef.setnchannels(1)
		wavef.setsampwidth(2)
		wavef.setframerate(44100)
		wavef.writeframes(data)
```

I'm not sure how to figure out if the data contained in an "audio type 0" file is AAC, WAV, or MP3, but it looks like it could be any of them.

**Comment by SinZ163** [comment]
Valve removes the header from audio files identified as WAV too.
But based off our codebase they don't strip headers for AAC / MP3 meaning we could try and detect the type based off reading the headers inside the MemoryStream?

**Comment by mdiller** [comment]
Also worth noting! It looks like the rest of the data in `bitpackedsoundinfo` might be incorrect. For the file I mentioned above, the value of `bitpackedsoundinfo` was `0x0100AC44`. From that, it read in that `SampleSize` is 6, which I'm pretty sure is wrong. Definetly looks like `SampleSize` is 2.  Also it says Channels is 0. I guess the format of `bitpackedsoundinfo` changes depending on the type?

ToString shows:
```

{
	uint32 m_bitpackedsoundinfo = 0x0100AC44
	int32 m_loopStart = -1
	float32 m_flDuration = 2.414671
}

Sample Rate: 1026
Bits: 17
Type: AAC
SampleSize: 6
Format: 2
Channels: 0
```

**Comment by mdiller** [comment]
So I've been taking some looks at this when I have free time, and it looks like the way we read `m_bitpackedsoundinfo` might not be correct. We're currently using the `ExtractSub()` function to do some interesting bit parsing of it, but it might be simpler than that. One good indication of that is that the last four hex characters of the one I was talking about and the one linked at the beginning of this issue are `AC44`, which in big endian is exactly `44100` which is an extremely common sampling frequency. It seems like a pretty big coincidence. 

Anyway, my question is where / how did we initially come up with the current way we're reading values out of this `m_bitpackedsoundinfo`? And while I'm asking, how did we know that the NTRO headers contain `m_bitpackedsoundinfo`, `m_loopStart`, and `m_flDuration`? (note that m_flDuration seems to also be inaccurate? not 100% sure, but the mp3 file at the beginning of this issue has a m_flDuration of 2.645125 but the mp3 duration is 1.993)

**Comment by xPaw** [comment]
I think it came from looking at Valve's resourceinfo or Dota 2 tools, but I don't remember at this point.

**Comment by mdiller** [comment]
Ok gotcha. I might take a look this weekend and see if I can find some more meaning in the data.

**Comment by mdiller** [comment]
I created a new pull request for this that should fix it. I did a whole bunch of analysis of the files and I think I extracted all the data from the new format of this `bitpackedsoundinfo` as I could.
