### ISSUE TITLE
Is there any document or example to explain how to use decompiler?

### ISSUE THREAD

**Issue by Seraphli** [SteamDatabase/ValveResourceFormat#119]
The command line help only displays options. Is there any example for extract files from a vpk file or extract raw materials from a vtex_c file?

**Comment by xPaw** [comment]
There isn't.

**Comment by Seraphli** [comment]
Can you provide some examples?

**Comment by xPaw** [comment]
https://github.com/SteamDatabase/GameTracking/blob/master/common.sh

This has some examples that should give you an idea.

**Comment by Seraphli** [comment]
Thank you. I read the shell script and figure out how to use.
