### ISSUE TITLE
cannot open vtex_c file

### ISSUE THREAD

**Issue by phamtheson01** [SteamDatabase/ValveResourceFormat#121]

**Comment by phamtheson01** [comment]
another request: 
1.add option to export vmesh_c to smd
2.add option to export vanim_c to smd

**Comment by xPaw** [comment]
"cannot open vtex_c file" literally doesn't say anything. If you are trying to report a bug provide clear details, what issue you have and what file is causing it.

The other comment is a duplicate of #102

**Comment by phamtheson01** [comment]
i'm uploading the details :)

**Comment by phamtheson01** [comment]
updated the detail

**Comment by phamtheson01** [comment]
i'm using the newest version

**Comment by xPaw** [comment]
Sounds like you have missing dlls, try to download last version or the one before if that doesn't work.

**Comment by AveYo** [comment]
It's the skiasharp external library, has a bug with not copying all dlls in the release folder.
Should be fixed in newer versions but that requires updating the project files
@OP just search for the libskiasharp.dll is around 6MB size and place it in the release directory

**Comment by xPaw** [comment]
@AveYo SkiaSharp dlls are in the VRF GUI.zip.
