### ISSUE TITLE
How to use decompiler (beginner stuff)?

### ISSUE THREAD

**Issue by snajdovski** [SteamDatabase/ValveResourceFormat#125]
Any guide for beginners I don't know where to start I have puted vxml_c file inside the folder and ran .bat it opens and closes no output nor sign of working am I missing something?
Also I opened up the bat file and there is something about .net required but I think I have that installed or I need to put somekind of file inside the folder I dont know I hope someone can point out, I know that is boring to repeat noob questions but hey I cant figure it out so why not type in a long message like this one :)

**Comment by xPaw** [comment]
You can use the GUI (VRF).

The Decompiler.bat is a CLI, so you need to run it in a separate terminal/console window to see its output.

**Comment by Ciberusps** [comment]
#101

**Comment by snajdovski** [comment]
@xPaw I dont understand can I edit vxml_c files somehow ? As I can see VRF is a .dll file and the gui is just a basic viewer how I can edit the files?
