### ISSUE TITLE
Command for decompiling  .vxml_c file

### ISSUE THREAD

**Issue by snajdovski** [SteamDatabase/ValveResourceFormat#126]
What is the syntax for decompiling vxml.c files?
Also is it possible to recompile?

**Comment by xPaw** [comment]
You can use the GUI to view and export.

Use Valve's own tooling to recompile.

**Comment by snajdovski** [comment]
@xPaw How is the offical tool called?

**Comment by xPaw** [comment]
What tool?

**Comment by snajdovski** [comment]
from Valve :/

**Comment by xPaw** [comment]
I don't know, all the stuff is in Dota 2 workshop tools.

You can lookup tutorials for that.

**Comment by snajdovski** [comment]
Thanks man found what I needed!

**Comment by Harrypotterrrr** [comment]
> Thanks man found what I needed!

Hi bro, could you plz tell me which tool you use to decompile the vxml_c ?
