### ISSUE TITLE
Generate tree structure for resource blocks

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#14]

**Comment by SinZ163** [comment]
Progress report:

|Name|Progress|Comments|
|-------|------------|--------------|
|NTRO|Partial|Missing arguably the most important bit of info, the fields.|
|RERL|Done|Minor issues regarding being able to adjust sizing of header to the state where its unreadable.|
|REDI|Not Started|Not sure how this one would work with its more-or-less independent tables|
|DATA|Not Started|This tab probably doesn't require one, as it will be format dependent|
|VBIB|Not Started|We don't even know what this block is yet, so its hard to visualize it.|

**Comment by xPaw** [comment]
We sort of do this already.
