### ISSUE TITLE
R11_EAC and RG11_EAC textures formats

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#144]
What we don't support:
```
        BC6H = 19,
        BC7 = 20,
        ATI2N = 21,
        ETC2 = 23,
        ETC2_EAC = 24,
        R11_EAC = 25,
        RG11_EAC = 26,
        ATI1N = 27,
```

Valve uses https://github.com/google/etc2comp

**Comment by xPaw** [comment]
Out of these, Underlords only uses ETC2 and ETC2_EAC

**Comment by xPaw** [comment]
ETC2 and ETC2_EAC are implemented, and the remaining formats have not been seen used anywhere.

**Comment by Rectus** [comment]
The new SteamVR beta updates have added a lightmap baker to the tools. The output of it gets saved as vtex_c files compressed with BC6H and BC7 inside the map vpk.

**Comment by xPaw** [comment]
Can you upload an example file?

**Comment by Rectus** [comment]
https://drive.google.com/open?id=173tAi7CmLA-C-l4647IAB9OEAtI_68TR
Here is the set of two it generates, as well as the .exr source files that the lightmapper caches (not sure which or if any of them get compiled directly). 

It seems a lot like the Unity directional lightmapper, storing one texture with lighting data + one with the direction of the dominant incoming dir and the directionality ratio in the alpha.

**Comment by xPaw** [comment]
Are you able to upload png images of the source so it's easier to compare what it's supposed to look like? Thanks.

**Comment by xPaw** [comment]
SteamVR has ATI1N textures:
materials/default/default_metal_tga_9e174e3d.vtex_c
materials/default/default_ao_tga_559f1ac6.vtex_c

in `\SteamVR\tools\steamvr_environments\game\core\pak01_dir.vpk`

**Comment by xPaw** [comment]
HL:A has ATI2N textures.

ATI1N textures sometiems crash with Index was outside the bounds of the array.

**Comment by xPaw** [comment]
Hey @lewa-j, perhaps you would like to take a look at ATI1N/ATI2N texture formats? I added code for ATI1N some time ago, and it doesn't appear to be fully correct as it crashes on certain textures in HL:A.

**Comment by lewa-j** [comment]
Alright. But i need sample textures, especially those that crashes.

**Comment by xPaw** [comment]
In HL'a VPK some ati1n textures that crash:
materials/models/props/plastic_barrel_1_ao_tga_2850e499.vtex_c
materials/models/props/plastic_tiling_rough_tga_e0c24fc1.vtex_c
materials/models/props/hotel/hotel_laundry_cart001_ao_tga_b83eddab.vtex_c
metro_body_ao_tga_58b6a7f3.vtex_c

ati2n textures:
materials/models/props/hotel/hotel_tarp_001_freedom_psd_993397bd.vtex_c
materials/models/props/misc_debris/debris_piles_med_normal_tga_2446c4a8.vtex_c
materials/xen/tile/antlion_infestation_blend_normal_tga_d5e4101f.vtex_c

Also, I noticed that BC7 decoder produces some corrupted images (like some pixels are not fully decoded or something), for example:
metro_body_normal_tga_e5bc8f85.vtex_c

**Comment by lewa-j** [comment]
Thanks. I'll look into it.
I tested BC7 decoder only on lightmaps.

**Comment by lewa-j** [comment]
#206 Should fix corruption on BC7 textures. It was related to alpha.

**Comment by lewa-j** [comment]
ATI1N done
![img](https://user-images.githubusercontent.com/5416122/77464359-193e3880-6e18-11ea-9b32-68745006ecbe.png)

**Comment by lewa-j** [comment]
ATI2N done. They share a lot of code with DXT5. Can be refactored.
![img](https://user-images.githubusercontent.com/5416122/77467401-024e1500-6e1d-11ea-9856-9a58bf872ff9.png)
![img](https://user-images.githubusercontent.com/5416122/77467391-feba8e00-6e1c-11ea-83cd-06558236b407.png)

**Comment by lewa-j** [comment]
Decoding NormalizeNormals just like DXT5
![img](https://user-images.githubusercontent.com/5416122/77471359-2ca2d100-6e23-11ea-8d12-4f3375ec8357.png)

**Comment by xPaw** [comment]
`sky_space_hdr.vtex_c` in hlvr using BC6H looks corrupted to me:
![image](https://user-images.githubusercontent.com/613331/78003450-51c2a280-7341-11ea-840b-ee00b2fc1316.png)

**Comment by lewa-j** [comment]
This is odd. light_sky_c17_zoo.vtex_c has the same format and all the other parameters and looks fine. Need to investigate.

**Comment by xPaw** [comment]
A lot of BC6H textures in HLA are broken (in skybox folder), it does feel like it has something to do with the (un)compressed sizes.
