### ISSUE TITLE
Can't fully parse Underlords auto save file (Binary KV3)

### ISSUE THREAD

**Issue by barrett777** [SteamDatabase/ValveResourceFormat#161]
This is somewhat out of my expertise so I'm speculating some.

Using code something like this:

```
var a = new ValveResourceFormat.ResourceTypes.BinaryKV3();

var b = new ValveResourceFormat.Resource();

using (var file = File.OpenRead(@"autosave.kv3"))
using (var binaryReader = new BinaryReader(file))
{
     a.Size = (uint) file.Length;

     a.Read(binaryReader, b);
}
```

I follow along and am able to parse a good portion of the attached file, somewhere up around stream position 8000.

Then it blows up because it reads a 'stringID' of 67108864 here:
https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/Resource/ResourceTypes/BinaryKV3.cs#L267

Suspiciously, just before this we were reading individual booleans from the stream for the first time, which makes me think the issue may be here:
https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/Resource/ResourceTypes/BinaryKV3.cs#L286

I wonder if we should be aligning to the next byte somewhere in this general area, but I've done a lot of trial and error and can't figure it out.

Any help would be greatly appreciated :)

**Comment by barrett777** [comment]
Ok some progress just to update on where I'm at:

If you take out the 'reader.ReadBoolean()' on this line: https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/Resource/ResourceTypes/BinaryKV3.cs#L286

It seems to finish parsing the file successfully.

I'm not sure what that means :)  Perhaps this case in the switch statement is not actually 'BOOLEAN', or perhaps I've accidentally worked around a separate issue related to aligning to a byte.

I'll look through the parsed results some more and see if the data is as I expect.  I only have one autosave file to work with at the moment.

Are you sure the BOOLEAN_TRUE and BOOLEAN_FALSE cases in this switch statement are at the correct place in the enum?

**Comment by barrett777** [comment]
Well the rest of the data looks legit to me.  In this file in particular, the only use of 'ReadBoolean()' is used on properties related to AI preferences (I believe), so I don't know what the actual values should be.  I'm going to leave this alone for now, as I don't really care about this particular property in my case, and there's a good chance Valve changes things soon'ish anyway, considering how new this game is

**Comment by Perryvw** [comment]
Which file are you trying to parse? I don't see any attached file. I'm reopening this issue because this sounds like a bug.

**Comment by xPaw** [comment]
I manually constructed a resource file so Valve's resourceinfo could dump it.

We correctly process up to this part:
```
				m_vecKnights = [  ]
				m_bUnitKeywords = 
				[
					false, false, false, false,
					false, false, false, true,
					false, false, false, true,
					false, false, false, true,
					false, false, false, false,
					false, false, false, false,
					true,
				]
```

`m_bUnitKeywords` correctly contains 25 booleans, but it gets the wrong string id when trying to read the next keyvalue: `m_nLowestPowerLevel = 1`
