### ISSUE TITLE
Trying to decode Underlords replay file

### ISSUE THREAD

**Issue by barrett777** [SteamDatabase/ValveResourceFormat#168]
While playing a match in Underlords, there is a 'demoheader.tmp' file that grows in size.

I assume this is a replay file, though replay files haven't yet been added to the game.  It is on their list of features coming soon on their home page though (underlords.com)

I would love to be able to decode this, but I haven't been able to make any progress on my own.

The file starts with 48-A2-D2-06.  I haven't been able to find any file format / magic string that looks like that.

If you edit the file in Notepad, there's several ~10 character human-readable chunks of text, which makes me think the file is not compressed.

I'm not sure what to try now.  Do you have any ideas for what kind of file format this is?

Since Underlords is using the Source 2 engine, I'd like to believe it isn't a home-grown replay format, but rather something that already exists in Source 2.

Any help would be greatly appreciated

[demoheader.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/3363756/demoheader.zip)

**Comment by xPaw** [comment]
Try looking at https://developer.valvesoftware.com/wiki/Dota_2_Demo_Format and https://github.com/ValveSoftware/csgo-demoinfo
