### ISSUE TITLE
vtex format 28

### ISSUE THREAD

**Issue by tnjtest2** [SteamDatabase/ValveResourceFormat#171]
### Describe the bug
Valve added new vtex format and textures are no longer displayed.

> System.NotImplementedException: Unhandled image type: 28
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap()
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input, Package currentPackage)

### Reference file in a Valve game
Dota 2 `game/dota/pak01_dir/panorama/images/items/moon_shard_png.vtex_c`

### Version info
0.0.15

**Comment by xPaw** [comment]
resourceinfo doesn't know what the format is called, but it can dump it to a tga just fine.

**Comment by xPaw** [comment]
Considering Valve added Cairo/Pixman licenses, it could be one of these:

https://afrantzis.com/pixel-format-guide/pixman.html
https://afrantzis.com/pixel-format-guide/cairo.html

**Comment by IdcNoob** [comment]
I believe they have BGRA8888 format.

**Comment by xPaw** [comment]
You're right it looks like it. Did you guess?
