### ISSUE TITLE
Unrecognized block types MRPH MDAT MBUF in vmdl

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#175]
Dota 2.

models/heroes/snapfire/snapfire.vmdl_c
models/heroes/snapfire/snapfire_body.vmdl_c

**Comment by Perryvw** [comment]
snapfire.vmdl also contains (or links to?) the ANIM block (#173) and another unrecognized ASEQ block.

**Comment by xPaw** [comment]
Here's the resourceinfo dump:
```

--- Resource Blocks: Count 13 ---
	-- Block 0: MRPH 	Size: 5,750        bytes [+10b padding]
	-- Block 1: MDAT 	Size: 12,065       bytes [+15b padding]
	-- Block 2: MBUF 	Size: 62,896       bytes [+0b padding]
	-- Block 3: MDAT 	Size: 12,061       bytes [+3b padding]
	-- Block 4: MBUF 	Size: 34,488       bytes [+8b padding]
	-- Block 5: ANIM 	Size: 1,751,683    bytes [+13b padding]
	-- Block 6: ASEQ 	Size: 4,947        bytes [+13b padding]
	-- Block 7: AGRP 	Size: 7,373        bytes [+3b padding]
	-- Block 8: PHYS 	Size: 8,335        bytes [+1b padding]
	-- Block 9: CTRL 	Size: 329          bytes [+3b padding]
	-- Block 10: RERL 	Size: 1,053        bytes [+3b padding]
	-- Block 11: REDI 	Size: 8,167        bytes [+13b padding]
	-- Block 12: DATA 	Size: 6,465        bytes [+0b padding]
```

MDAT has m_sceneObjects/drawCalls etc
MRPH is kv3
MBUF is VBIB i think
ANIM is kv3, has m_animArray / m_pData / fps etc
ASEQ is kv3, has m_localSequenceNameArray 
AGRP is kv3, has m_decodeKey
PHYS is kv3, has m_pFeModel / m_CtrlHash
CTRL is kv3, has embedded_meshes <- this is the metadata block

**Comment by xPaw** [comment]
I refactored the library code to support the new blocks, just need to update the renderer to actually understand it.
