### ISSUE TITLE
Decompiler should either not accept folders without --recursive or not rely on it

### ISSUE THREAD

**Issue by DatGuy1** [SteamDatabase/ValveResourceFormat#177]
In Decompiler.cs#L328, if --recursive is not supplied then outputFile is the name of the directory at L710 rather than the name of the file inside the directory, and in turn throws UnauthorizedException. It's possible though that someone would want to scan a directory without --recursive to avoid subfolders. Imo best course of action is just adding a IsFile boolean and replacing RecursiveSearch with that at L328

**Comment by xPaw** [comment]
Passing a folder without --recursive will do what you're suggesting (scan just the folder). Sounds like an oversight in the dumping though.
