### ISSUE TITLE
Dota2 vmdl_c animation[vanim_c] error

### ISSUE THREAD

**Issue by or75** [SteamDatabase/ValveResourceFormat#178]
```
System.IO.FileNotFoundException: Failed to load models/heroes/abaddon/73c484d0/idle.vanim_c. Did you configure game paths correctly?
   в GUI.Types.Renderer.Animation.AnimationGroupLoader.LoadAnimationGroup(Resource resource, String path)
   в GUI.MainForm.ProcessFile(String fileName, Byte[] input, Package currentPackage)
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
```

file 'models/heroes/abaddon/73c484d0/idle.vanim_c' has exist

file: dota/pak01_dir/models/heroes/abaddon/abaddon.vmdl_c
and all other hero models o_O

ResourceFormatVersion: 0.0.16.828

![image](https://user-images.githubusercontent.com/5619678/72751349-74fa0480-3bd0-11ea-868e-590ff0dfb142.png)

![image](https://user-images.githubusercontent.com/5619678/72751338-6e6b8d00-3bd0-11ea-88db-fb7a1437fea8.png)

**Comment by xPaw** [comment]
"Did you configure game paths correctly?"

Specify the path to pak01_dir.vpk in settings.

**Comment by Perryvw** [comment]
> "Did you configure game paths correctly?"
> 
> Specify the path to pak01_dir.vpk in settings.

Should it not search in the currently opened vpk (which seems to be pak01_dir.vpk) by default?

**Comment by xPaw** [comment]
It does on master: https://github.com/SteamDatabase/ValveResourceFormat/commit/aed300692d2b3674dc282fa9641620326dac70d4
