### ISSUE TITLE
No option to disable transparency in texture viewer

### ISSUE THREAD

**Issue by AlpyneDreams** [SteamDatabase/ValveResourceFormat#194]
### Describe the bug
Often, textures will have an alpha channel. Newer versions of VRF will always render that as transparency with a black background, which for many textures results in difficulty viewing and is not consistent with how Source 2 displays them:
![ValveResourceViewer_2020-03-04_19-18-09](https://user-images.githubusercontent.com/3376691/75944570-e6260c00-5e4c-11ea-9a6c-a17990c59a4d.png)

### Reference file in a Valve game
Many `vtex_c` files in the Half-Life: Alyx SteamVR environment/asset pack VPKs have alpha channels that are not even encoding transparency information.
Example: `2006656803.vpk\materials\architecture\c17\c17_plaster_hs01a_mural_color_tga_387777a8.vtex_c`
In this example the alpha channel is just solid 0.5 and is clearly not supposed to represent transparency as this is an opaque material.

### Expected behavior
A checkbox to disable rendering transparency in the texture viewer would resolve this issue.

Additionally, an option to view the individual RGB or A channels (some textures have specific information in specific channels other than color/normal) would also be useful, Source 2's native Asset Viewer does this for textures:
![image](https://user-images.githubusercontent.com/3376691/75945262-90526380-5e4e-11ea-84e5-c836d951a828.png)

### Version info
Most recent versions, including 0.1.0
In 0.0.6 (and possibly newer versions than that) transparency was not implemented and textures could be viewed more easily.

**Comment by SinZ163** [comment]
As a partial workaround, you could go in the settings menu and change background colour to white

**Comment by xPaw** [comment]
> In this example the alpha channel is just solid 0.5 and is clearly not supposed to represent transparency as this is an opaque material.

I'm not so sure about that.

c17_plaster_hs01a_mural_color_tga_390fad6f.vtex_c looks fine, and the material uses both of these textures, so it most likely blends between the two.

> As a partial workaround, you could go in the settings menu and change background colour to white

I don't think that works for textures.

**Comment by DankParrot** [comment]
The thing is that those two textures are actually compiled from the same input file (according to the material's REDI). And they aren't different layer colors, although they're both referenced, I'm not entirely sure how it uses both of them but that alpha information clearly isn't supposed to represent _transparency_ even if it is used for something else like blending.

**Comment by lewa-j** [comment]
It also affects skybox textures in steamvr_environments/game/core/pack01_dir.vpk
They are completely blank. If i set alpha to byte.MaxValue in ReadRGBA16161616F, i see them.
![img](https://user-images.githubusercontent.com/5416122/77440453-60690100-6df9-11ea-8648-acd032b6384d.png)
But this is not the solution. Some textures need alpha for transparency, some don't.

**Comment by DankParrot** [comment]
Another example in HL:A is `pak01_dir/models/valve_head/materials/valve_head_color_tga_574ec893.vtex_c`

**Comment by DankParrot** [comment]
Additionally I think it'd be useful to be able to export RGB and Alpha as separate files because that'd be closer to how the content files are set up before compilation.
