### ISSUE TITLE
Decompiling VMDL_C files from HLA

### ISSUE THREAD

**Issue by IAmPiggggg** [SteamDatabase/ValveResourceFormat#203]
Hi, i'm really sorry as i'm sure this is asked a lot, but can anyone help me with decompiling the alyx pistol to an obj or fbx etc, cheers!

**Comment by CodeF53** [comment]
Extracting the Stuff
1. Open ``common\Half-Life Alyx\game\hlvr\pak01_dir.vpk`` in VRF
2. navigate to ``Models\Weapons\vr_alyxgun``, 
3. rightclick and decompile and export on said folder
4. rightclick export on said folder (export to the same place as step 3)

Prepping files for conversion
1. Open SteamVR
2. (hamburger menu)>```Workshop-Create/Modify an Environment```
3. Create an empty addon with any name you please
4. Navigate to ```common\SteamVR\tools\steamvr_environments\game\steamtours_addons\example``` in file explorer
5. Drag and drop the extracted ``model`` folder from vrf into said folder
6. in the steamvr tools thing, click on the folder you made and click launch tools

Converting Files
1. Click on the hammer icon in the upper left of the asset browser
2. Create a new map (file new)
3. (bottom middle of hammer) click on the models tab and search for the desired model
4. drag and drop the model into the environment 
5. (Bottom Right of hammer) (Object Propertys) unfold the transform tab
6. Set origin to 0,0,0
7. Right Click on model in the hammer window
8. (right click menu) Selected Entity's > Convert Models to Editable Mesh
9. File > Export Selected
10. change ''save as type'' to FBX or OBJ
11. save

**Comment by Zoidberg656** [comment]
> Extracting the Stuff
> 
> 1. Open `common\Half-Life Alyx\game\hlvr\pak01_dir.vpk` in VRF
> 2. navigate to `Models\Weapons\vr_alyxgun`,
> 3. rightclick and decompile and export on said folder
> 4. rightclick export on said folder (export to the same place as step 3)
> 
> Prepping files for conversion
> 
> 1. Open SteamVR
> 2. (hamburger menu)>`Workshop-Create/Modify an Environment`
> 3. Create an empty addon with any name you please
> 4. Navigate to `common\SteamVR\tools\steamvr_environments\game\steamtours_addons\example` in file explorer
> 5. Drag and drop the extracted `model` folder from vrf into said folder
> 6. in the steamvr tools thing, click on the folder you made and click launch tools
> 
> Converting Files
> 
> 1. Click on the hammer icon in the upper left of the asset browser
> 2. Create a new map (file new)
> 3. (bottom middle of hammer) click on the models tab and search for the desired model
> 4. drag and drop the model into the environment
> 5. (Bottom Right of hammer) (Object Propertys) unfold the transform tab
> 6. Set origin to 0,0,0
> 7. Right Click on model in the hammer window
> 8. (right click menu) Selected Entity's > Convert Models to Editable Mesh
> 9. File > Export Selected
> 10. change ''save as type'' to FBX or OBJ
> 11. save

There isn't an examples folder inside steamtours_addons.

**Comment by Zoidberg656** [comment]
Well, regardless of it being closed, I'm hoping my lack of "example" folder can be explained.

**Comment by kevinivek** [comment]
You are locating the folder for the steamvr environment you created, so go to `common\SteamVR\tools\steamvr_environments\game\steamtours_addons\NAME YOU USED IN STEP 3`

**Comment by Perryvw** [comment]
You can also directly export the vmesh (not vmdl!) to OBJ using the export menu inside VRF.

**Comment by kevinivek** [comment]
> You can also directly export the vmesh (not vmdl!) to OBJ using the export menu inside VRF.

You can, but I haven't seen any vmesh in HL:A, seems the mesh data is contained in the vmdl in this new version of source 2. I could be completely wrong as I only have recently been looking into it.

**Comment by CodeF53** [comment]
Imbicle

I mean the folder named the thing you named your thing in steamvr.

**Comment by Zoidberg656** [comment]
> You are locating the folder for the steamvr environment you created, so go to `common\SteamVR\tools\steamvr_environments\game\steamtours_addons\NAME YOU USED IN STEP 3`

I created a few in the little "SteamVR Workshop Tools, Custom Environments" popup underneath "Addon Name", but no folders appear inside that destination.

**Comment by Zoidberg656** [comment]
Fixed my problem. SteamVR wasn't using my old hard-drive directory.

But each model I import into Hammer turns into a big orange ERROR.

**Comment by KaesarZZ** [comment]
Mm When I click on "Launch Tools" it says my SteamVR is outdated. Ofc it's updated and I've tested the actually beta version 1.11.2. 

https://i.gyazo.com/3039311fcb87653c7402cef330c68fd0.png

Any help?

**Comment by CodeF53** [comment]
Updating to beta fixed that for me

**Comment by ScienceMarc** [comment]
> Mm When I click on "Launch Tools" it says my SteamVR is outdated. Ofc it's updated and I've tested the actually beta version 1.11.2.
> 
> https://i.gyazo.com/3039311fcb87653c7402cef330c68fd0.png
> 
> Any help?

You need to have your HMD to actually use the tools for some reason.

**Comment by UnionOfUniverses** [comment]
> Fixed my problem. SteamVR wasn't using my old hard-drive directory.
> 
> But each model I import into Hammer turns into a big orange ERROR.
> Even the same Alyx gun that this thread was discussing. Error.

Same. What we need to do?

**Comment by xPaw** [comment]
I'm locking this issue because it turned into some catch-all discussion for issues that aren't directly related to VRF.
