### ISSUE TITLE
Bug with rendering some models

### ISSUE THREAD

**Issue by 5FB5** [SteamDatabase/ValveResourceFormat#205]
![Screenshot_1](https://user-images.githubusercontent.com/15859698/77425931-8df77f80-6de4-11ea-9d4f-f828b4d10e84.png)

### Describe the bug
Some models VRF viewer can't render correctly and look like cheese. Nothing printed in console about this.

### Reference file in a Valve game
Half-Life Alyx\game\hlvr\pack01_dir.vpk\models\characters\gman\gman_split.vmdl

### Version info
ver. 0.1.1
Windows 10

**Comment by xPaw** [comment]
This is fixed in unstable build.
