### ISSUE TITLE
Decompression errors on some BC7 textures in HLA

### ISSUE THREAD

**Issue by DankParrot** [SteamDatabase/ValveResourceFormat#218]
### Describe the bug
Related: #219 and previously #144
Some textures don't seem to be correctly displayed in the texture viewer or on export.

The colors are incorrect and there are heavy artifacts that are not supposed to be there like this:
![image](https://user-images.githubusercontent.com/3376691/77838318-e05bd780-7127-11ea-9c64-e9d231a146bc.png)

Their blocky shape and polarized colors makes me think they are artifacts from reading the compressed image wrong.

### Reference file in a Valve game

`models/props/quarantine/materials/combine_sign_cleanup_color_tga_ff0ed443.vtex_c`

This is how the texture looks when extracted, after removing the alpha channel (which stores metalness I think, so just the RGB).
<img alt="combine_sign_cleanup_color_tga_ff0ed443_BROKEN" src="https://user-images.githubusercontent.com/3376691/77838524-9a077800-7129-11ea-8442-eb95d4d242ab.png" width="256">

The AO of this material (`combine_sign_cleanup_ao_tga_f076dc04.vtex_c`) is also broken; it looks kinda like scanlines or something. Its format is ATI1N, not BC7, see #219.

### Expected behavior
Here's what `combine_sign_cleanup.vmat_c` looks like in the material viewer. This is also how it looks ingame. This material uses no other color textures, so this is roughly how the texture above is supposed to look.
<img alt="combine_sign_cleanup_color_tga_ff0ed443_BROKEN" src="https://user-images.githubusercontent.com/3376691/77838584-21ed8200-712a-11ea-82c6-8169b5bb7fa7.png" width="256">

### Version info
Tested with v.1.0.0.36337

**Comment by DankParrot** [comment]
Here's what resourceinfo gives when used with `-fullmip`

Still not sure if the color saturation is correct. It may be the material is that much darker because of the AO texture which is also broken.

<img alt="combine_sign_cleanup_color_tga_ff0ed443" src="https://user-images.githubusercontent.com/3376691/77839232-c1f9da00-712f-11ea-9976-95b446c3fa1f.jpg" height=512 width=512>

**Comment by xPaw** [comment]
It's probably losing saturation due to alpha transparency, so it's a different issue.

And I think the corruptness is fixed in #217.
