### ISSUE TITLE
Decompression errors on some ATI1N textures in HLA

### ISSUE THREAD

**Issue by DankParrot** [SteamDatabase/ValveResourceFormat#219]
### Describe the bug
Related: #218 and previously #144
Some textures don't seem to be correctly displayed in the texture viewer or on export.

### Reference file in a Valve game

`models/props/quarantine/materials/combine_sign_cleanup_ao_tga_f076dc04.vtex_c`

This is how the texture looks when extracted by VRF.
<img alt="combine_sign_cleanup_ao_tga_f076dc04.vtex_c" src="https://user-images.githubusercontent.com/3376691/77839513-477e8980-7132-11ea-98b9-8ade2cf17522.png" width="256">

- Looks kind of like scanlines or something? Every 2px line alternates between colors and pure black.
- Also the blue channel seems different to the other two despite this texture being AO
- This will also look fucky in an image viewer or in your browser due to the moiré effect, so zoom in

### Expected behavior
This is how that texture looks in the asset viewer.

<img alt="combine_sign_cleanup_ao_tga_f076dc04.vtex_c fixed" src="https://user-images.githubusercontent.com/3376691/77839627-51ed5300-7133-11ea-8751-bf9917d6b289.png" width="256">

Asset browser says there's only one channel (in the dropdown box), and it's displayed as if it were the red channel.

Trying to use SteamVR's `resourceinfo` on this vtex_c will actually cause it to fail with the following error:
`Error converting from ATI1N to RGBA8888`

### Version info
Tested with v.1.0.0.36337

**Comment by DankParrot** [comment]
Another example with the same issue, same format:
`materials/xen/tile/xen_web_dead001_blendmask_inverted_psd_198938cd.vtex_c`

<img alt="xen_web_dead001_blendmask_inverted_psd_198938cd" width="256" src="https://user-images.githubusercontent.com/3376691/77839986-09d02f80-7137-11ea-8bb1-0f6fd2782013.png">

**Comment by DankParrot** [comment]
Found it on an ATI2N texture as well.

`materials/xen/tile/xen_regen01_normal_tga_e4631ac0.vtex_c`

<img alt="xen_regen01_normal_tga_e4631ac0" width="256" src="https://user-images.githubusercontent.com/3376691/77840484-e4462480-713c-11ea-8d3e-7885c075dfd4.png">

**Comment by xPaw** [comment]
All your examples are fixed in #217
