### ISSUE TITLE
Support exporting from vmdl (embedded meshes)

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#221]
We currently allow exporting from vmesh, but now that models can have embedded data, we should move extraction code onto vmdl directly, so it can export external and internal meshes directly.

**Comment by Lonswaya** [comment]
Obj doesn't support mesh groups, so we would be losing all animation information if we export straight to there. Exporting straight to a folder and exporting all other vmat/vtex would be the best option.

**Comment by xPaw** [comment]
We're working on exporting to glTF: https://github.com/SteamDatabase/ValveResourceFormat/tree/gltf
