### ISSUE TITLE
Add a setting to disable the model viewer grid

### ISSUE THREAD

**Issue by OciXCrom** [SteamDatabase/ValveResourceFormat#225]
I'm aware this isn't very important at the moment, but can we add an option to disable the grid when using the model viewer? It's for video recording purposes.

![img](https://i.imgur.com/7EIN5hu.png "img")

Thanks.

**Comment by xPaw** [comment]
There's already a boolean to hide grid in code, just need to add a checkbox in the model viewer.

**Comment by OciXCrom** [comment]
Thanks for the quick response!
