### ISSUE TITLE
Add ability to dock tabs

### ISSUE THREAD

**Issue by DatGuy1** [SteamDatabase/ValveResourceFormat#230]

**Comment by xPaw** [comment]
What's the use case?

**Comment by DatGuy1** [comment]
Wanting to compare between REDI/DATA section of two different files, wanting to go through two different vpks and see if files are missing from one. Could be done by just opening another window of the GUI but docking seems better to me.

**Comment by xPaw** [comment]
Seems like an awful lot of work in winforms for little gain.

**Comment by xPaw** [comment]
Closing, as this is unlikely to be implemented.
