### ISSUE TITLE
Help on converting vmdl to other model formats

### ISSUE THREAD

**Issue by CL3NRc** [SteamDatabase/ValveResourceFormat#236]
I have tried everything. i tried searching the internet, i tried making discussions, i tried several different programs, i tried contacting people, and now im trying this. i really really REALLY need to know how to convert the half life alyx vmdl converted model format to other model formats like fbx, or even mdl but i have no clue where or how to do that. any advice?

**Comment by xPaw** [comment]
There's already open issues about exporting models (to gltf).
