### ISSUE TITLE
'Export' and 'Save As' (right click) don't do the same thing.

### ISSUE THREAD

**Issue by DankParrot** [SteamDatabase/ValveResourceFormat#238]
### Describe the bug
When viewing a texture, 'Right click-> Save as...' gives the user png/jpeg/tiff/bmp options but regardless of the format it always comes out incorrectly like #218 

When using the 'Export' menu bar button, only png is an option and this texture exports correctly.

This has caused serious headaches as I was struggling to figure out why exporting only worked right sometimes.

### Reference file in a Valve game
From HL:A
`models/props/quarantine/materials/combine_sign_cleanup_breen_color_tga_c9c436f8.vtex_c`

This was the example from #218 and you can use it with both methods to see how 'Save As' is borken.

### Expected behavior
They should probably do the exact same thing.

### Version info
Tested with version v0.1.3.1171 (gltf branch I think) on Windows 10.

### Additional context
See #218.

**Comment by xPaw** [comment]
Can't repro, using right click->save as I get the same picture as displayed in VRF (that's what the 'save as' does), so its not corrupted.
