### ISSUE TITLE
Material export not open in material editor 

### ISSUE THREAD

**Issue by pvp-by** [SteamDatabase/ValveResourceFormat#239]
### Describe the bug

after export vmat_c to vmat and not open in 

### Reference file in a Valve game
Dota 2 `game/dota/pak01_dir/materials/models/props_gameplay/halloween_candy.vmat_c

### Expected behavior
open in editor result after decompile

### Version info
0.1.3.1175

### Additional context
see image from npp++
completely different files

![image](https://user-images.githubusercontent.com/10133995/78985453-e6938000-7b39-11ea-9e32-c820a9e86e7c.png)

**Comment by xPaw** [comment]
We don't have material exporting, so pull requests welcome from anyone that wants to implement it.

**Comment by xPaw** [comment]
I wrote some code here https://github.com/SteamDatabase/ValveResourceFormat/tree/vmat-kv1 to export it into kv1, give it a try.

**Comment by pvp-by** [comment]
![image](https://user-images.githubusercontent.com/10133995/83725160-88bf7800-a652-11ea-8900-a08a0cf4c924.png)
not work , 
need control decompile save UTF8 - with out BOM (see image 2)
![image](https://user-images.githubusercontent.com/10133995/83748508-5b36f680-a673-11ea-8303-76abb992f283.png)



diff after decompile
![image](https://user-images.githubusercontent.com/10133995/83748254-f4b1d880-a672-11ea-9578-8ea0d2c037f8.png)

**Comment by xPaw** [comment]
Your screenshot in first post has g_tColor in material too, where did TextureColor from?

If you fix BOM, does TextureColor or g_tColor work?

**Comment by pvp-by** [comment]
WITH OUT fix:
![image](https://user-images.githubusercontent.com/10133995/83843074-4f9c0c00-a715-11ea-92ba-27459e42447c.png)

BOM fix only open file.
all path for image ignored , and change default меучю
but the setting activated the desired areas.
![image](https://user-images.githubusercontent.com/10133995/83842380-e1a31500-a713-11ea-82d6-778119a49cb6.png)

> where did TextureColor from

image original source :
![image](https://user-images.githubusercontent.com/10133995/83843354-dd77f700-a715-11ea-8fd1-57fd2ae62974.png)

after "save" or "save as" : 
![image](https://user-images.githubusercontent.com/10133995/83843594-63943d80-a716-11ea-8f0a-22d1a5a7d21f.png)

**Comment by lewa-j** [comment]
> меучю

You mean vtex.

**Comment by pvp-by** [comment]
yes sorry

**Comment by xPaw** [comment]
Let me clarify, now that BOM is fixed, the material opens correctly in the editor, except that you need to change texture paths?

Texture paths not working is kinda expected because it points to vtex, instead of the original files.
