### ISSUE TITLE
Dota 2 map is not correctly rendered

### ISSUE THREAD

**Issue by BogdanDumi** [SteamDatabase/ValveResourceFormat#260]
SW: VRF
Build version: 0.1.4.1244

Action:
1. Load any dota 2 map package (e.g. : dota_722.vpk)
2. Open file world.vwrld_c

Expected: Map should be rendered successfully (with texture)

Observed:  Map is not rendered as expected.

![not_rendered](https://user-images.githubusercontent.com/68294340/87455360-fb3a5500-c60d-11ea-8701-fc4f4db2b1d7.png)

**Comment by xPaw** [comment]
Add the dota pak01 in settings.
