### ISSUE TITLE
Broken pixels on DXT5 non-power-of-two textures

### ISSUE THREAD

**Issue by win98se** [SteamDatabase/ValveResourceFormat#264]
### Describe the bug
Many of Dota 2's item icons have loss of pixels in the first column of the file after decompiled.
![ultimate_scepter_tease2_png](https://user-images.githubusercontent.com/11819816/87511483-ed391280-c6a7-11ea-8c1e-d39e2100a748.png)
In addition, some item icons (usually with black backgrounds) don't even has 88\*64 pixels anymore, for example `place_building_png.vtex_c` (74\*64), `pocket_tower_png.vtex_c` (74\*64), `gauntlets_png.vtex_c` (81\*64), `monkey_king_bar_png.vtex_c` (84\*64) and `chainmail_png.vtex_c` (85\*64).

All of the above still renders fine in game.

### Reference file in a Valve game
- Dota 2 `game/dota/pak01_dir/panorama/images/items/*.vtex_c`
- Dota 2 `game/dota_addons/aghanim/panorama/images/items/*.vtex_c`

### Expected behavior
All pixels should be intact after decompiled.

### Version info
VRF 0.1.4.1263 on Windows 10 Version 2004 Build 19041.329

### Additional context
This has worked for previous versions of the game, but not in this version.

**Comment by xPaw** [comment]
> In addition, some item icons (usually with black backgrounds) don't even has 88*64 pixels anymore, for example

These icons do not say that they are 88x64, the size VRF extracts is correct as specified by the texture.

**Comment by win98se** [comment]
OK, seems like this _problem_ (for me, it is) doesn't happen just recently. I've checked with 2 old copies I have (versions 3839 [7.22h] and 3947 [7.23f]), the _problems_ are also there.

I was saying that “some item icons don't even has 88\*64 pixels anymore” because I referred to [this page](https://dota2.gamepedia.com/Category:Item_icons), and all (except 2) are in 88\*64 (in their File History, mostly it reads “original img size”). The first column of all the icons on that page are fine, except [this one](https://dota2.gamepedia.com/File:Aghanim%27s_Scepter_(2020_Summer_Event)_icon.png).

> As for loss of pixels, you need to specify which files exactly get that problem.

There are too lot of them. FYI, the image shown above is Dota 2 `game/dota/pak01_dir/panorama/images/items/ultimate_scepter_tease2_png.vtex_c`.

262 of 321 files under Dota 2 `game/dota/pak01_dir/panorama/images/items` are affected -
- `abyssal_blade_png.vtex_c`
- `aegis_png.vtex_c`
- `aeon_disk_png.vtex_c`
- `aether_lens_png.vtex_c`
- `ancient_janggo_png.vtex_c`
- `arcane_boots2_png.vtex_c`
- `arcane_boots_png.vtex_c`
- `arcane_ring_png.vtex_c`
- `armlet_active_png.vtex_c`
- `armlet_png.vtex_c`
- `assault_png.vtex_c`
- `band_of_elvenskin_png.vtex_c`
- `basher_png.vtex_c`
- `belt_of_strength_png.vtex_c`
- `bfury_png.vtex_c`
- `black_king_bar_png.vtex_c`
- `blades_of_attack_png.vtex_c`
- `blade_mail_png.vtex_c`
- `blade_of_alacrity_png.vtex_c`
- `blight_stone_png.vtex_c`
- `blink_png.vtex_c`
- `blitz_knuckles_png.vtex_c`
- `bloodstone_png.vtex_c`
- `bloodthorn_png.vtex_c`
- `boots_of_elves_png.vtex_c`
- `boots_png.vtex_c`
- `bottle4_png.vtex_c`
- `bottle_arcane_png.vtex_c`
- `bottle_empty_png.vtex_c`
- `bottle_haste_png.vtex_c`
- `bottle_illusion_png.vtex_c`
- `bottle_invisibility_png.vtex_c`
- `bottle_medium_png.vtex_c`
- `bottle_png.vtex_c`
- `bottle_regeneration_png.vtex_c`
- `bottle_small_png.vtex_c`
- `bracer_png.vtex_c`
- `branches_png.vtex_c`
- `broadsword_png.vtex_c`
- `buckler_active_png.vtex_c`
- `buckler_png.vtex_c`
- `butterfly_png.vtex_c`
- `chainmail_png.vtex_c`
- `cheese_png.vtex_c`
- `circlet_png.vtex_c`
- `clarity_png.vtex_c`
- `claymore_png.vtex_c`
- `cloak_png.vtex_c`
- `combo_breaker_png.vtex_c`
- `courier_dire_flying_png.vtex_c`
- `courier_dire_png.vtex_c`
- `courier_png.vtex_c`
- `courier_radiant_flying_png.vtex_c`
- `courier_radiant_png.vtex_c`
- `craggy_coat_png.vtex_c`
- `crown_png.vtex_c`
- `cyclone_2_png.vtex_c`
- `cyclone_png.vtex_c`
- `dagon_2_png.vtex_c`
- `dagon_3_png.vtex_c`
- `dagon_4_png.vtex_c`
- `dagon_5_png.vtex_c`
- `dagon_png.vtex_c`
- `default_png.vtex_c`
- `demon_edge_png.vtex_c`
- `desolator_png.vtex_c`
- `diffusal_blade_png.vtex_c`
- `dimensional_doorway_png.vtex_c`
- `dragon_lance_png.vtex_c`
- `dust_png.vtex_c`
- `eagle_png.vtex_c`
- `echo_sabre_png.vtex_c`
- `elixer1_png.vtex_c`
- `elixer2_png.vtex_c`
- `elixer3_png.vtex_c`
- `elixer4_png.vtex_c`
- `elixer_png.vtex_c`
- `enchanted_mango_png.vtex_c`
- `energy_booster_png.vtex_c`
- `essence_ring_png.vtex_c`
- `es_arcana_blink_png.vtex_c`
- `es_arcana_blink_ult2_png.vtex_c`
- `ethereal_blade_png.vtex_c`
- `ex_machina_png.vtex_c`
- `faded_broach_png.vtex_c`
- `faerie_fire_png.vtex_c`
- `flask2_png.vtex_c`
- `flask_png.vtex_c`
- `flying_courier_png.vtex_c`
- `force_staff_png.vtex_c`
- `gauntlets_png.vtex_c`
- `gem_of_true_sight_png.vtex_c`
- `gem_png.vtex_c`
- `ghost_scepter_png.vtex_c`
- `gloves_of_haste_png.vtex_c`
- `gloves_png.vtex_c`
- `greater_clarity_png.vtex_c`
- `greater_crit_png.vtex_c`
- `greater_faerie_fire_png.vtex_c`
- `greater_mango_png.vtex_c`
- `greater_salve_png.vtex_c`
- `grove_bow_png.vtex_c`
- `guardian_greaves_png.vtex_c`
- `hand_of_midas_ogre_arcana_png.vtex_c`
- `hand_of_midas_png.vtex_c`
- `headdress_png.vtex_c`
- `heart_png.vtex_c`
- `heavens_halberd_png.vtex_c`
- `helm_of_iron_will_png.vtex_c`
- `helm_of_the_dominator_png.vtex_c`
- `helm_of_the_undying_png.vtex_c`
- `holy_locket_enemy_png.vtex_c`
- `holy_locket_png.vtex_c`
- `hood_of_defiance_png.vtex_c`
- `horizon_png.vtex_c`
- `hurricane_pike_png.vtex_c`
- `hyperstone_png.vtex_c`
- `illusionsts_cape_png.vtex_c`
- `infused_raindrop_png.vtex_c`
- `invis_sword_png.vtex_c`
- `iron_talon_png.vtex_c`
- `javelin_png.vtex_c`
- `kaya_and_sange_png.vtex_c`
- `kaya_png.vtex_c`
- `lesser_crit_png.vtex_c`
- `lifesteal_png.vtex_c`
- `maelstrom_png.vtex_c`
- `magic_stick_png.vtex_c`
- `magic_wand_png.vtex_c`
- `manta_png.vtex_c`
- `mantle_png.vtex_c`
- `mask_of_madness_png.vtex_c`
- `medallion_of_courage_png.vtex_c`
- `mekansm_png.vtex_c`
- `meteor_hammer_png.vtex_c`
- `minotaur_horn_png.vtex_c`
- `mithril_hammer_png.vtex_c`
- `mjollnir_png.vtex_c`
- `monkey_king_bar_png.vtex_c`
- `mutation_tombstone_png.vtex_c`
- `mystic_staff_png.vtex_c`
- `necronomicon_2_png.vtex_c`
- `necronomicon_3_png.vtex_c`
- `necronomicon_png.vtex_c`
- `nether_shawl_png.vtex_c`
- `neutral_png.vtex_c`
- `ninja_gear_png.vtex_c`
- `nullifier_png.vtex_c`
- `null_talisman_png.vtex_c`
- `oblivion_staff_png.vtex_c`
- `ogre_axe_png.vtex_c`
- `orb_of_destruction_png.vtex_c`
- `orb_of_venom_png.vtex_c`
- `orchid_png.vtex_c`
- `paladin_sword_png.vtex_c`
- `pers_png.vtex_c`
- `phase_boots_png.vtex_c`
- `philosophers_stone_png.vtex_c`
- `pipe_png.vtex_c`
- `place_building_png.vtex_c`
- `platemail_png.vtex_c`
- `pocket_roshan_png.vtex_c`
- `pocket_tower_png.vtex_c`
- `point_booster_png.vtex_c`
- `poor_mans_shield_png.vtex_c`
- `power_treads_agi_colorblind_png.vtex_c`
- `power_treads_agi_png.vtex_c`
- `power_treads_int_png.vtex_c`
- `power_treads_png.vtex_c`
- `power_treads_str_png.vtex_c`
- `princes_knife_png.vtex_c`
- `quarterstaff_png.vtex_c`
- `quelling_blade_png.vtex_c`
- `quickening_charm_png.vtex_c`
- `radiance_inactive_png.vtex_c`
- `radiance_png.vtex_c`
- `rapier_png.vtex_c`
- `reaver_png.vtex_c`
- `recipe_png.vtex_c`
- `refresher_png.vtex_c`
- `refresher_shard_png.vtex_c`
- `relic_png.vtex_c`
- `repair_kit_png.vtex_c`
- `ring_of_aquila_active_png.vtex_c`
- `ring_of_aquila_png.vtex_c`
- `ring_of_basilius_active_png.vtex_c`
- `ring_of_basilius_png.vtex_c`
- `ring_of_health_png.vtex_c`
- `ring_of_protection_png.vtex_c`
- `ring_of_regen_png.vtex_c`
- `ring_of_tarrasque_png.vtex_c`
- `river_painter2_png.vtex_c`
- `river_painter3_png.vtex_c`
- `river_painter4_png.vtex_c`
- `river_painter5_png.vtex_c`
- `river_painter6_png.vtex_c`
- `river_painter7_png.vtex_c`
- `river_painter_png.vtex_c`
- `robe_png.vtex_c`
- `rod_of_atos_png.vtex_c`
- `royal_jelly1_png.vtex_c`
- `royal_jelly2_png.vtex_c`
- `royal_jelly_png.vtex_c`
- `salve_png.vtex_c`
- `sange_and_yasha_png.vtex_c`
- `sange_png.vtex_c`
- `satanic_png.vtex_cx`
- `sheepstick_png.vtex_c`
- `shivas_guard_png.vtex_c`
- `silver_edge_png.vtex_c`
- `skadi_png.vtex_c`
- `slippers_of_halcyon_png.vtex_c`
- `slippers_png.vtex_c`
- `smoke_of_deceit_png.vtex_c`
- `sobi_mask_png.vtex_c`
- `solar_crest_png.vtex_c`
- `soul_booster_png.vtex_c`
- `soul_ring_png.vtex_c`
- `spell_prism_png.vtex_c`
- `sphere_png.vtex_c`
- `spirit_vessel_png.vtex_c`
- `spy_gadget_png.vtex_c`
- `staff_of_wizardry_png.vtex_c`
- `stout_shield_png.vtex_c`
- `super_blink_png.vtex_c`
- `talisman_of_evasion_png.vtex_c`
- `tango_png.vtex_c`
- `tango_single_png.vtex_c`
- `the_leveller_png.vtex_c`
- `third_eye_png.vtex_c`
- `tombstone_png.vtex_c`
- `tome_of_knowledge_png.vtex_c`
- `tpscroll_png.vtex_c`
- `tranquil_boots_active_png.vtex_c`
- `tranquil_boots_png.vtex_c`
- `travel_boots_2_png.vtex_c`
- `travel_boots_png.vtex_c`
- `ultimate_orb_png.vtex_c`
- `ultimate_scepter_2_png.vtex_c`
- `ultimate_scepter_png.vtex_c`
- `ultimate_scepter_tease2_png.vtex_c`
- `ultimate_scepter_tease_png.vtex_c`
- `urn_of_shadows_png.vtex_c`
- `vambrace_agi_png.vtex_c`
- `vambrace_int_png.vtex_c`
- `vambrace_png.vtex_c`
- `vambrace_str_png.vtex_c`
- `vampire_fangs_png.vtex_c`
- `vanguard_png.vtex_c`
- `veil_of_discord_png.vtex_c`
- `vitality_booster_png.vtex_c`
- `vladmir_png.vtex_c`
- `void_stone_png.vtex_c`
- `voodoo_mask_png.vtex_c`
- `ward_dispenser_png.vtex_c`
- `ward_dispenser_sentry_png.vtex_c`
- `ward_observer_png.vtex_c`
- `ward_sentry_png.vtex_c`
- `woodland_striders_png.vtex_c`
- `wraith_band_png.vtex_c`
- `yasha_and_kaya_png.vtex_c`
- `yasha_png.vtex_c`

71 of 79 files under Dota 2 `game/dota_addons/aghanim/panorama/images/items` are affected -
- `aghsfort_drow_ranger_invis_sword_png.vtex_c`
- `aghsfort_refresher_shard_png.vtex_c`
- `ambient_sorcery_png.vtex_c`
- `amorphotic_shell_png.vtex_c`
- `arcane_fragments_png.vtex_c`
- `bag_of_gold_png.vtex_c`
- `bandit_archer_shadow_blade_png.vtex_c`
- `battle_points_png.vtex_c`
- `bear_cloak_png.vtex_c`
- `bogduggs_baldric_png.vtex_c`
- `bogduggs_cudgel_png.vtex_c`
- `bogduggs_lucky_femur_png.vtex_c`
- `book_of_agility_png.vtex_c`
- `book_of_greater_agility_png.vtex_c`
- `book_of_greater_intelligence_png.vtex_c`
- `book_of_greater_strength_png.vtex_c`
- `book_of_intelligence_png.vtex_c`
- `book_of_strength_png.vtex_c`
- `boots_png.vtex_c`
- `broadsword_png.vtex_c`
- `carapace_of_qaldin_png.vtex_c`
- `chainmail_png.vtex_c`
- `cloak_png.vtex_c`
- `corrupting_blade_png.vtex_c`
- `creature_black_king_bar_png.vtex_c`
- `creed_of_omniscience_png.vtex_c`
- `dragon_potion_png.vtex_c`
- `dredged_trident_png.vtex_c`
- `energy_booster_png.vtex_c`
- `glimmerdark_shield_png.vtex_c`
- `gravel_foot_png.vtex_c`
- `greater_clarity_png.vtex_c`
- `greater_salve_png.vtex_c`
- `guardian_shell_png.vtex_c`
- `health_potion_png.vtex_c`
- `hyperstone_png.vtex_c`
- `ice_dragon_maw_png.vtex_c`
- `lifesteal_png.vtex_c`
- `lifestone_png.vtex_c`
- `life_rune_png.vtex_c`
- `longclaws_amulet_png.vtex_c`
- `mana_potion_png.vtex_c`
- `nether_shawl_png.vtex_c`
- `oblivions_locket_png.vtex_c`
- `ogre_seal_totem_png.vtex_c`
- `paw_of_lucius_png.vtex_c`
- `pelt_of_the_old_wolf_png.vtex_c`
- `phoenix_sheepstick_png.vtex_c`
- `power_treads_png.vtex_c`
- `precious_egg_png.vtex_c`
- `preserved_skull_png.vtex_c`
- `purification_potion_png.vtex_c`
- `ravage_potion_png.vtex_c`
- `rhyziks_eye_png.vtex_c`
- `sign_of_the_arachnid_png.vtex_c`
- `slippers_of_the_abyss_png.vtex_c`
- `stonework_pendant_png.vtex_c`
- `stony_coat_png.vtex_c`
- `talisman_of_evasion_png.vtex_c`
- `the_caustic_finale_png.vtex_c`
- `tombstone_png.vtex_c`
- `tome_of_greater_knowledge_png.vtex_c`
- `treads_of_ermacor_png.vtex_c`
- `treasure_box_png.vtex_c`
- `ultimate_orb_png.vtex_c`
- `ultimate_scepter_2_png.vtex_c`
- `unhallowed_icon_png.vtex_c`
- `vitality_booster_png.vtex_c`
- `wand_of_the_brine_png.vtex_c`
- `watchers_gaze_png.vtex_c`
- `winter_embrace_png.vtex_c`

> And are you sure Dota workshop tools don't do this?

I've searched for methods using official tools to decompile the `.vtex_c`s, but I get horrible results. I don't know how to do it. :/

**Comment by xPaw** [comment]
Yeah I tested 0.1.1 and the pixels are not there on left. `royal_jelly2_png` is texture I'm using to check that.

I think this commit broke it: https://github.com/SteamDatabase/ValveResourceFormat/commit/8fcc512bfc320d30ffd7266f4cdc77a3e3a1d8ea

@lewa-j mind helping?

**Comment by lewa-j** [comment]
Sure

**Comment by lewa-j** [comment]
This only affects an alpha channel. So I noticed only after exporting the file.

**Comment by win98se** [comment]
Using 0.1.4.1268 (although the latest version right now is 0.1.4.1270) solved it. Thank you, @xPaw and @lewa-j!
