### ISSUE TITLE
VTexFormat.RGBA8888 showing wrong colours

### ISSUE THREAD

**Issue by SinZ163** [SteamDatabase/ValveResourceFormat#27]
Test file: `panorama/images/profile_badges/level_15.png.vtex_c`

![](http://i.imgur.com/N8aTnqn.png)

(Normally something like ![](http://i.imgur.com/Egz6GSY.png))

**Comment by xPaw** [comment]
That means this is incorrect: https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/ThirdParty/DDSImage.cs#L248
