### ISSUE TITLE
Dota minimap sheet doesn't export into normal color

### ISSUE THREAD

**Issue by heyimrendy** [SteamDatabase/ValveResourceFormat#283]
### Describe the bug
Not entirely sure if this is intended but ```vtex_c``` from dota minimap doesn't export into normal color, it used to export into normal color.

### Reference file in a Valve game
From dota ```pak01_dir.vpk```
materials/vgui/hud/minimap_hero_sheet_psd_3529892a.vtex_c

### Expected behavior
Normal color when export into ```png``` from this file.

### Version info
Testing with latest releases from github, version 0.1.4 and 0.1.5

### Additional context
Version 0.1.3 from github releases export into normal color.

* Version 0.1.3 VRF GUI
![VRF GUI Version 0.1.3](https://user-images.githubusercontent.com/61161733/90856762-4ac81b00-e348-11ea-80db-d28721195a88.png)
* Version 0.1.5 VRF GUI
![VRF GUI Version 0.1.5](https://user-images.githubusercontent.com/61161733/90857125-12750c80-e349-11ea-9e19-bc03d2614d52.png)

**Comment by xPaw** [comment]
You are showing screenshots in GUI. So your complaint the transparent background?

**Comment by heyimrendy** [comment]
Not the background but the image result doesnt show as normal RGB color. For comparison, the export results:

* v0.1.3
![v0 1 3](https://user-images.githubusercontent.com/61161733/90860620-f0cb5380-e34f-11ea-831d-e007f1c5c9ec.png)
* v0.1.5
![v0 1 5](https://user-images.githubusercontent.com/61161733/90860628-f45eda80-e34f-11ea-8f42-8d3a02271b6f.png)

**Comment by xPaw** [comment]
Well I just bisected it, and it came back to a commit that updated SkiaSharp.

```
➜ git bisect bad
466f5760938115850b99055657fb4de130d68051 is the first bad commit
commit 466f5760938115850b99055657fb4de130d68051
Author: Pavel Djundik <xPaw@users.noreply.github.com>
Date:   Sun Jul 12 11:36:55 2020 +0300

    Update packages

 Decompiler/Decompiler.csproj                   | 2 +-
 GUI/GUI.csproj                                 | 4 ++--
 Tests/Tests.csproj                             | 2 +-
 ValveResourceFormat/ValveResourceFormat.csproj | 4 ++--
 4 files changed, 6 insertions(+), 6 deletions(-)
```
