### ISSUE TITLE
BC6H sky_space_hdr.vtex_c in HLVR is corrupted when decompressing

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#284]
### Describe the bug

![image](https://user-images.githubusercontent.com/613331/78003450-51c2a280-7341-11ea-840b-ee00b2fc1316.png)

### Reference file in a Valve game
materials/skybox/sky_space_hdr.vtex_c
materials/skybox/sky_space_hdr_exr_7aa94ac8.vtex_c

It has cubemap flags, could be related to that.

cc @lewa-j for help

**Comment by xPaw** [comment]
There's more textures in skybox/tests/src, some work, some don't.

**Comment by xPaw** [comment]
maps/a2_train_yard/cubemaps/env_cubemap_array.vtex_c is also corrupted.

**Comment by lewa-j** [comment]
![img](https://user-images.githubusercontent.com/5416122/125833705-ae47716e-ba2a-4854-bb76-d94523efe097.png)
![img](https://user-images.githubusercontent.com/5416122/125833843-3abf31cb-3c56-4413-bbf6-b0ec6cf0c579.png)
