### ISSUE TITLE
Switch to .NET native Half type

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#287]
https://devblogs.microsoft.com/dotnet/introducing-the-half-type/

This should remove `ValveResourceFormat.HalfTypeHelper`

**Comment by ch-asimakopoulos** [comment]
Can I take a crack at this?

**Comment by xPaw** [comment]
Sure. Keep in mind .NET 5 does not have extension methods to read halfs in BinaryReader.

**Comment by ch-asimakopoulos** [comment]
@xPaw  how about this?

**Comment by xPaw** [comment]
You can give it a try where half type helper is called, I am unsure.
