### ISSUE TITLE
vtex_c files which contain TGA compressed with DXT5 have incorrect colors when decompressed

### ISSUE THREAD

**Issue by babelshift** [SteamDatabase/ValveResourceFormat#29]
After some testing and research, I've found that the vtex_c files which are incorrectly colored on extraction are TGA files compressed with DXT5 and possibly in YCoCg colorspace.

Looking at the REDI tab reveals:

CResourceString m_String = "Texture Compiler Version Image YCoCg Conversion"

This is a bit out of my league. I'm not sure if Valve's texture compiler is converting to YCoCg colorspace prior to compression. Maybe that means it needs to be read out as YCoCg and converted to RGB during decompression?

Github doesn't support attaching vtex_c, but here's a test file that you can see. https://drive.google.com/file/d/0B7o2acNuwX44X01LZnVUeFZfX2c/view?usp=sharing

Attached to this issue is the results of decompressing the file linked above.
![loadingscreen_tga](https://cloud.githubusercontent.com/assets/2723423/11454121/7978eb00-95f0-11e5-831e-e69ad2013569.png)

**Comment by SinZ163** [comment]
Part of the problem is the use of alpha, and ValveResourceViewer has a white background (dota always has a black background).  But there is still a colour issue.

**Comment by babelshift** [comment]
The alpha channel seems off in addition to the colors. I saved it out of ValveResourceViewer as a png and viewed it in Paint.NET. Colors and alpha looked weird there as well. I played around with converting between colorspaces with ImageMagick, but I don't think it supports YCoCg.

**Comment by xPaw** [comment]
There has to be some information besides compiler identifier stored for this. Have you tried finding a DXT5 file with RGB color scheme, if one exists?

**Comment by babelshift** [comment]
I did look but only on a limited (manual) basis. I might try to create something that goes through the vpk and checks for the compression and color spaces automatically.

**Comment by babelshift** [comment]
Some info from this thread which might be relevant: http://dev.dota2.com/showthread.php?t=182677&page=2

> Okey.
 
> Good news. The format used`s definitely YCgCo (https://en.wikipedia.org/wiki/YCgCo). I`ve managed to compile a YCgCo formatted image using it`s Valve-spinoff, and my Dota 2 client displayed it correctly. The schema Valve`s using`s the following:
> R: Co
> G: Cg
> B: Edit: Nope, it`s not Alpha. It`s .. something. Can`t discern what, tho.
> A: Y

**Comment by xPaw** [comment]
@babelshift Could you attach a screenshot showing how your attached texture should look? If you can't do with provided texture in first post, you can find another one.

**Comment by babelshift** [comment]
Here's the best I could find of it.

![cosmetic_icon_three_heroes_loading_screen](https://cloud.githubusercontent.com/assets/2723423/11507274/3ad3313e-9821-11e5-8f33-5ef6fb3cf3dc.png)

**Comment by xPaw** [comment]
Oh wow, our colors are definitely off.

Do you mind finding another tga example (with ingame screenshot) in dota files?

**Comment by babelshift** [comment]
Here's a file from `\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk`.

Path in VPK: `\panorama\images\econ\announcer\announce_axe_png.vtex_c`

In Game: 
![announcer_axe_ingame](https://cloud.githubusercontent.com/assets/2723423/11507955/769faee2-9824-11e5-87b2-4660ab88a5fd.png)

Extracted:
![announcer_axe_png](https://cloud.githubusercontent.com/assets/2723423/11507897/2f26fb42-9824-11e5-874b-a8c8d84a84f4.png)

The aspect ratio seems wrong on this one when extracted as well. Extracted is a 256x256 square, but the in game is a wide ratio.

**Comment by xPaw** [comment]
I don't have dota installed at the moment, could you attach it please?

**Comment by babelshift** [comment]
GitHub doesn't let me attach non-images, so here's a link to it on my Google Drive.

https://drive.google.com/file/d/0B7o2acNuwX44NmVwMHNvVm9lTDQ/view?usp=sharing

**Comment by xPaw** [comment]
Well I believe I fixed the colors.

Diff:
```diff
@@ -248,6 +248,16 @@ private static void DecompressBlockDXT5(int x, int y, int width, byte[] blockSto
                             break;
                     }
 
+                    int co = finalColor.R - 128;
+                    int cg = finalColor.G - 128;
+
+                    finalColor = Color.FromArgb(
+                        finalAlpha,
+                        ClipColor(finalAlpha + co - cg),
+                        ClipColor(finalAlpha + cg),
+                        ClipColor(finalAlpha - co - cg)
+                    );
+
                     if (x + i < width)
                     {
                         image.SetPixel(x + i, y + j, finalColor);
@@ -256,5 +266,16 @@ private static void DecompressBlockDXT5(int x, int y, int width, byte[] blockSto
             }
         }
         #endregion
+
+        private static int ClipColor(int a)
+        {
+            if (a > 255)
+                return 255;
+
+            if (a < 0)
+                return 0;
+
+            return a;
+        }
     }
 }
```

![announcer_axe_png](https://cloud.githubusercontent.com/assets/613331/11509684/37c24e5c-9868-11e5-8c73-7647aefe8a05.png)
![loadingscreen_tga](https://cloud.githubusercontent.com/assets/613331/11509685/39987ce2-9868-11e5-8434-19dd3dc904ca.png)

**Comment by babelshift** [comment]
I integrated your diff and can confirm the better colors. I wasn't happy with the diff so I noticed in the ffmpeg functions that an alpha of `255` is used when `scaling == 1`. Since your diff used `b >> 3` as the scaling factor, which is also used when `scaling == 1`, I decided to override the `finalAlpha` with `255` to match. That produced the attached image, which appears to be perfect to me.

![loadingscreen_tga](https://cloud.githubusercontent.com/assets/2723423/11520946/d63c8784-9875-11e5-9ad0-9c838c083d48.png)

**Comment by babelshift** [comment]
And here's the announcer pack image, which also appears identical to the ingame shot above. However, the aspect ratio is still off (haven't addressed that yet).

![announcer_axe_png](https://cloud.githubusercontent.com/assets/2723423/11521009/5848bedc-9876-11e5-81a0-755c45930363.png)

**Comment by SinZ163** [comment]
is ingame ![](http://i.imgur.com/BhJx8b0.jpg)
is ValveResourceViewer before @xPaw's diff ![](http://i.imgur.com/2gF9vhP.png)

Using @xPaw's diff 

is ValveResourceViewer respecting Alpha![](http://i.imgur.com/p7OD91y.png) 
is ValveResourceViewer with alpha hardcoded to `0xFF`![](http://i.imgur.com/JezcztS.jpg)

**Comment by xPaw** [comment]
Interesting. So the image isn't actually transparent?
