### ISSUE TITLE
Weird unhandled exception after map load

### ISSUE THREAD

**Issue by SamboyCoding** [SteamDatabase/ValveResourceFormat#307]
### Describe the bug

Following on from my bug #305 I managed to load the distillery map, and upon finishing loading got another unhandled exception:
```
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.Enter(Object obj)
   at OpenTK.Input.Mouse.GetState()
   at GUI.Controls.GLViewerControl.Draw() in C:\projects\valveresourceformat\GUI\Controls\GLViewerControl.cs:line 256
   at GUI.Controls.GLViewerControl.OnGotFocus(Object sender, EventArgs e) in C:\projects\valveresourceformat\GUI\Controls\GLViewerControl.cs:line 286
   at System.Windows.Forms.Control.OnGotFocus(EventArgs e)
```

Clicking continue causes this to pop back up, but continuing once more allows the map to be viewed without further incident. I'm not sure if this is a bug in VRF or in OpenTK, but I just thought it best to report here.

### Reference file in a Valve game

Half-Life: Alyx `game/hlvr/maps/a3_distillery.vpk/maps/a3_distillery/world.vwrld_c`

### Expected behavior

No error pop-up, I am just able to fly around the map.

### Version info

VRF v0.1.6.1395

### Additional context

N/A

**Comment by xPaw** [comment]
Does this happen every time? Does it happen on smaller/other maps?

**Comment by SamboyCoding** [comment]
It happens fairly regularly on this map and on the vault map, not so much on smaller maps - for example, the hotel_lobby_basement map has never thrown this error

**Comment by xPaw** [comment]
Gonna close this because I don't see a way for us to fix this.
