### ISSUE TITLE
Can't Decompile And Export Models From Entire Folders

### ISSUE THREAD

**Issue by Ameno-Sagiri** [SteamDatabase/ValveResourceFormat#312]
### Describe the bug
When you right click a model in the resource viewer (a .vmdl_c file), you can click decompile & export. This then exports the model as a gltf along with the textures. However, my issue is, I'm trying to export entire folders from HL: Alyx. When I right click a folder and hit Decompile & Export, the behavior of the program isn't as expected. Instead of mass decompiling and exporting said folder, it instead just runs an export on all the models, exporting them as .vmdl files. I want to mass decompile and export everything inside a folder as gltf and textures.

### Reference file in a Valve game
Half-Life Alyx Models

### Expected behavior
I expect when I right click and decompile export a models folder, it will decompile and export every single model in said folder as gltf model format and textues. Similarly, this works when decompiling and exporting sounds folders and materials folders, it's SPECIFICALLY only the models folders that won't mass decompile.

### Version info
v0.1.6.1353
Bug Also Present in V0.1.6.1399

### Additional context
None

**Comment by phamtheson01** [comment]
the tool did correctly what it should do, however, the ".vmdl" extension is the decompiled one for official valve's tool ( the workshop tool )
you could ask them to support the feature you wanted

**Comment by xPaw** [comment]
Fixed by #448
