### ISSUE TITLE
CLI can't decompile vmdl_c to glTF - Invalid KV3 signature

### ISSUE THREAD

**Issue by faust-hub** [SteamDatabase/ValveResourceFormat#313]
### Describe the bug
Can't cli decompile to glTF many models after update Dota2 in Nov
Throw error: "Invalid KV3 signature 1263940354 on resource type vmdl_c, extracting as-is"

### Reference file in a Valve game
`game/dota/pak01_dir/models/heroes/batrider/batrider.vmdl_c`
`game/dota/pak01_dir/models/heroes/life_stealer/life_stealer.vmdl`
`game/dota/pak01_dir/models/heroes/sven/sven.vmdl`
etc.

### Expected behavior
An exported glTF file

### Version info
VRF Decompiler 0.1.6.1353, Win7

### Additional context
console output:
![Снимок](https://user-images.githubusercontent.com/65903670/101979553-0356f900-3c6f-11eb-9285-97c8df538897.JPG)

**Comment by xPaw** [comment]
Use latest unstable build.
