### ISSUE TITLE
Add image format argument for export vtex_c files in Decompiler

### ISSUE THREAD

**Issue by GoranKovac** [SteamDatabase/ValveResourceFormat#327]
### Is your feature request related to a problem? Please describe.
By default decompiler exports images files to .png. If you want other format you need to do it manually or make a script:

for %%f in (%~1\*.vtex_c) do (
  C:\VRF\vrf_decompiler.bat -i %%~f -d -o %%~f.tga
)

### Describe the solution you'd like
Add new argument which format is set (TGA,PNG,JPG.....)
--export_image_format TGA

Decompiler.exe -i "\dota\pak01_dir.vpk" -o "C:\test" -d -e vtex_c -f materials/models/heroes/abaddon --export_image_format TGA

### Describe alternatives you've considered
None

### Additional context
None

**Comment by xPaw** [comment]
We don't support tga.
