### ISSUE TITLE
Wrong height in decompressed DXT5 images

### ISSUE THREAD

**Issue by babelshift** [SteamDatabase/ValveResourceFormat#33]
Here is an image as it appears on the Dota 2 CDN at http://cdn.dota2.com/apps/570/icons/econ/leagues/subscriptions_gpsea.c08851767ea252d6fcd993f3b0411c2f81f1d2d8.png

![subscriptions_gpsea_png_correct](https://cloud.githubusercontent.com/assets/2723423/11634929/776e3444-9ce1-11e5-8b97-8f20e06b7a28.png)

Here is that same image extracted from the Dota 2 VPK at pak01_dir.vpk/panorama/images/econ/leagues/subscriptions_gpsea_png.vtex_c

![subscriptions_gpsea_png_incorrect](https://cloud.githubusercontent.com/assets/2723423/11634969/aa500f7c-9ce1-11e5-8daa-9d67f39747b0.png)

You can see the height is off and the texture is stretched to compensate. I see this occurring on quite a few DXT5 compressed textures after they are decompressed.

**Comment by xPaw** [comment]
That's what the size indicates, I believe this used to be an issue in source 1 games too?

**Comment by babelshift** [comment]
Oh. I see now that some are stretched in the width direction, so the issue title is not entirely correct. Regardless, if the data indicates a wrong dimension, I'm not sure what we can do. Should I close the issue?

**Comment by xPaw** [comment]
It might be worth investigating if it's possible to fix it, if the game somehow knows how to render it correctly, although it will be related to the fact that they're rendered as textures, and the size is known separately.

**Comment by xPaw** [comment]
Since it's a texture, there's no way to cut it based on the texture alone.
