### ISSUE TITLE
Request decoding support for material dynamic expressions

### ISSUE THREAD

**Issue by mreak** [SteamDatabase/ValveResourceFormat#337]
Request decoding support for material dynamic expressions

```
m_dynamicParams = 
	[
		
		{
			m_name = "g_flSelfIllumScale"
			m_value = 
			#[
				07 CD CC 4C 3F 07 00 00 80 3F 06 20 00 08 00 07 00 00 80 3F 07 00 00 00 40 06 20 00 08 01 07 00
				00 00 00 07 00 00 80 3F 06 20 00 08 02 09 02 07 CD CC CC 3D 0F 04 3A 00 3F 00 09 00 02 41 00 09
				01 08 03 07 00 00 80 3F 09 03 15 07 00 00 80 3F 09 03 15 07 00 00 80 3F 09 03 15 06 19 00 08 04
				09 04 07 00 00 80 3F 15 00 
			]
		},
	]
```

**Comment by xPaw** [comment]
Follow the issue template. What game is this, what file, what does this do.

**Comment by mreak** [comment]
**Issues Description**
Request decoding support for material dynamic expressions

**game**
Source2 engine games including Half-life:Alyx , dota2, etc.

**Example files**
*.vmat_c
```
Half-life:Alyx material
materials/workshop_examples/monitor/screen_russell_desktop_12_example.vmat
```

```
Dota 2 material
materials/models/heroes/arc_warden/spark_wraith.vmat
```
![alyx_1](https://user-images.githubusercontent.com/11804437/110622735-cdc29d00-81d6-11eb-995e-86828d13a1d1.jpg)

![alyx_3](https://user-images.githubusercontent.com/11804437/110622946-18dcb000-81d7-11eb-8584-da241c4f334a.jpg)

![alyx_2](https://user-images.githubusercontent.com/11804437/110622743-d1eeba80-81d6-11eb-9c32-9668686bc03f.jpg)

**Comment by pvp-by** [comment]
not decoding, but additional information on the question
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Materials/Dynamic_Material_Expressions

**Comment by robert-hoff** [comment]
Hello, I can tell you a bit about this

In the bytestream the following should hold

`07 X X X X` 4 byte encoded float value, all values are floats without exception
`19 X X X X` reference to an external variable. In the example `19 CC 85 44 96` represents the variable **time**.
`13,14,15,16` are the arithmetic operators `+,-,*,\`
`06 XX 00` are function IDs, see table below
`08 XX` is an assignment `=` to a local variable (variables local to the textbox only)
`09 XX` are reference to the same local variables where used as part of an expression

To decode the bytestream read values from left to right. Values, or operator arguments, will appear _before_ the operation, all brackets are inferred (there are no bracket symbols). Arithmetic operators expect 2 arguments, all functions have a predetermined number of arguments (as in the table). Mismatch of argument lengths would mean error.

**Example**
```
r = floor((frac((time+20)/80)*4))*.25;
r = step(r,.5);
g = floor((frac((time-20)/80)*4))*.25;
g = step(r,.5);
b = floor((frac((time-40)/80)*4))*.25;
b = step(r,.5);
float3(r,g,b)
```

The first line of the source text ` r = floor((frac((time+20)/80)*4))*.25` is encoded as
`19 CC 85 44 96 07 00 00 A0 41 13 07 00 00 A0 42 16 06 03 00 07 00 00 80 40 15 06 04 00 07 00 00 80 3E 15 08 00`

`19 CC 85 44 96` is the variable `time`
`07 00 00 A0 41` = `20.0`
`13` means addition, applying the operator to the arguments we just read gives `(time+20)`
`07 00 00 A0 42` = `80.0`
`16` means division, using the same rule gives `((time+20)/80)`
`06 03 00` is the id for the function `frac(X)`, applying it gives `frac((time+20)/80)`
`07 00 00 80 40` = `4.0` and `15` means multiplication, giving `(frac((time+20)/80)*4)`
`06 04 00` is the id for floor(X), which gives `floor(frac((time+20)/80)*4)`
`07 00 00 80 3E` = `0.25` and `15`  again means multiplication: `floor(frac((time+20)/80)*4)*0.25`
`08 00` means equate expression to the local variable 0x00 which is 'r'. This is the final step for the top line.

`r = floor(frac((time+20)/80)*4)*.25`

**Notes**

(i) I don't think it's possible to recover the local variable names. (they are not in the bytestream anyway) (ii) The names of the variables with external references are listed in the DATA block for the `vmat_c` file. So it seems reasonable we can get names from there. For example the **time** variable = `19 CC 85 44 96`. However the bytes don't look like an offset or index to me, I don't know what their functional significance may be. (iii) The function list is incomplete they are just the ones I was able to find.

**Function reference**
(incomplete)
![image](https://user-images.githubusercontent.com/762237/126050305-a816b55c-74b3-4420-bf1e-8f66297b0bfb.png)

**Comment by xPaw** [comment]
Looked at materialsystem2 briefly, here's all the functions (in that order):
```
sin
cos
tan
frac
floor
ceil
saturate
clamp
lerp
dot4
dot3
dot2
log
log2
log10
exp
exp2
sqrt
rsqrt
sign
abs
pow
step
smoothstep
float4
float3
float2
time
min
max
SrgbLinearToGamma
SrgbGammaToLinear
random
normalize
length
sqrt
TextureSize
rotation2d
rotate2d
sincos
```
