### ISSUE TITLE
Can't decompile certain files

### ISSUE THREAD

**Issue by FlamePython** [SteamDatabase/ValveResourceFormat#353]
### Describe the bug

Can't decomplie some of the vmdl_c files. It starts to export the textures but stops when it should do the model.

### What Valve game does this happen in

Half-Life: Alyx

### Reference file in a Valve game

combine_strider.vmdl_c
combine_strider_construction.vmdl_c
headcrab_classic.vmdl_c

### Expected behavior

It should export and decompile them like the other files

### What version of VRF are you using? On what platform?

Both v0.1.7.1518 and v0.1.9.1561

**Comment by xPaw** [comment]
Include the error/log.

**Comment by CrazyHairGuy** [comment]
headcrab_classic.vmdl_c is the one mentioned in #309, which fails to export the model due to the 'value' error.

**Comment by FlamePython** [comment]
> Include the error/log.

Yeah, I forgot about that sorry. I updated it now.

**Comment by xPaw** [comment]
Duplicate of #309.
