### ISSUE TITLE
not working on windows 7

### ISSUE THREAD

**Issue by kereh** [SteamDatabase/ValveResourceFormat#356]
### Describe the bug

every time I open the application it always says "application stopped working" does vrf really can't be run on windows 7?

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

Dota Path
D:\steam\steamapps\common\dota 2 beta

### Expected behavior

I hope it works well on windows 7

### What version of VRF are you using? On what platform?

v0.1.9

**Comment by xPaw** [comment]
"application stopped working" is useless information we can't upon. Unless you can provide more details, not much can be done to help you here.

FYI, VRF is 64-bit only.
