### ISSUE TITLE
Bad header version Error

### ISSUE THREAD

**Issue by nonunknown** [SteamDatabase/ValveResourceFormat#359]
### Describe the bug

When executing: `./Decompiler -i "/run/media/nonunknown/3a1f3657-ce4a-4ffa-8f65-f41e1dfcaf68/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/csgo/pak01_001.vpk"`

The following error is shown:
```cs
System.IO.InvalidDataException: Bad header version. (7 != expected 12)
   at ValveResourceFormat.Resource.Read(Stream input)
   at Decompiler.Decompiler.ProcessFile(String path, Stream stream, String originalPath)
	Resource Type: Unknown [Version 0] [Header Version: 7]
	File Size: 4609110 bytes
```

### What Valve game does this happen in

CSGO

### Reference file in a Source 2 game

`Counter-Strike Global Offensive/csgo/pak01_001.vpk`

### Expected behavior

Decompile the file and get access to its contents.

### What version of VRF are you using? On what platform?

0.1.9 over Linux Manjaro GNOME

**Comment by xPaw** [comment]
You need to pass pak01_dir.
