### ISSUE TITLE
cli decompile to .vmdl

### ISSUE THREAD

**Issue by faust-hub** [SteamDatabase/ValveResourceFormat#361]
### Is your feature request related to a problem? Please describe.

How to get .vmdl DATA block from .vmdl_c, not .gltf in the new version of the cli decompiler? I need get records like: 
![image](https://user-images.githubusercontent.com/65903670/124511836-b63f9d80-dddf-11eb-84ea-13a7e66b6af1.png)

**Comment by xPaw** [comment]
--decompile

**Comment by faust-hub** [comment]
this does not work :,-(
example: Decompiler.exe --input "C:/Program Files (x86)/Steam/steamapps/common/dota 2 beta/game/dota/pak01_dir.vpk" --vpk_filepath "models/items/pudge/ti10_immortal_armhook/pudge_ti10_immortal_arm_hook.vmdl_c" --output result --decompile
result:
![image](https://user-images.githubusercontent.com/65903670/124512508-34507400-dde1-11eb-944b-fdf8898e0532.png)

**Comment by xPaw** [comment]
Yeah sorry, that is the option. (it being named vpk_ is a bit of a misname)

**Comment by faust-hub** [comment]
If i use "--vpk_decompile" then it exports to .gltf, but not .vmdl :((
How to get records DATA block?

**Comment by xPaw** [comment]
Try `--block DATA`?

**Comment by faust-hub** [comment]
I tried.
ex: Decompiler.exe --input "C:/Program Files (x86)/Steam/steamapps/common/dota 2 beta/game/dota/pak01_dir.vpk" --vpk_filepath "models/items/pudge/ti10_immortal_armhook/pudge_ti10_immortal_arm_hook.vmdl_c" --output result --block DATA
result - unpacked vmdl_c :((
what am I doing wrong?

**Comment by xPaw** [comment]
The output is gonna be in stdout, pipe it yourself.

**Comment by faust-hub** [comment]
In stdout only this:
![image](https://user-images.githubusercontent.com/65903670/124514087-eccbe700-dde4-11eb-8640-b97a16362d29.png)

**Comment by xPaw** [comment]
Don't use --output

**Comment by faust-hub** [comment]
In this case, it only gives me only a summary of the files in the package:
![image](https://user-images.githubusercontent.com/65903670/124514497-d83c1e80-dde5-11eb-86c8-69aa8736c7be.png)

**Comment by xPaw** [comment]
If you think your use case is missing, pull requests are welcome.

**Comment by faust-hub** [comment]
Well, it would be great if .vmdl_c could be exported not only to gltf, and simply to unpacked .vmdl (as in earlier versions decompiler - before support gltf)
