### ISSUE TITLE
Implement KeyValues

### ISSUE THREAD

**Issue by SinZ163** [SteamDatabase/ValveResourceFormat#37]
The following file formats are required to have the Decompiler write the decompiled formats, and to read some of the compiled formats:

- [ ] Plaintext KeyValues(1)
- [ ] Binary KeyValues(1)
- [ ] `dmx encoding keyvalues2_noids` (not sure if this should be in the KeyValues family or in its own DMX family)
- [x] KeyValues3 #35
- [ ] Schema text (not sure if its strictly speaking in the KeyValues family, as its header implies otherwise)
- [ ] Unit tests for each keyvalues implementation

**Comment by xPaw** [comment]
This tracking issue should be moved to https://github.com/SteamDatabase/ValveKeyValue
And then we would reference that library.
