### ISSUE TITLE
Huge model files export into too many glTF bin files

### ISSUE THREAD

**Issue by hrimthurs** [SteamDatabase/ValveResourceFormat#379]
### Describe the bug

When trying to decompile the model to gltf hangs at the stage "Found existing material" and generate many .bin files in out folder. Same result in gui and cli. On release version and unstable
![scr1](https://user-images.githubusercontent.com/65903670/134350295-c1c7eecf-04fd-45ed-a58d-27987aceaa2b.JPG)
![scr2](https://user-images.githubusercontent.com/65903670/134350330-890155ed-c351-4919-ab73-78dc4d9fa3d5.JPG)

.

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

models/items/spectre/spectre_arcana/spectre_arcana_base

### Expected behavior

Decompilated .gltf in out folder. As with other models.

### What version of VRF are you using? On what platform?

VRF 0.1.10.828, Win10 x64

**Comment by xPaw** [comment]
It's slow, have you waited long enough?

Can you press cancel to see anything in console?

**Comment by faust-hub** [comment]
I waited until there were too many files (120000 files summary 180Mb). Progress bar is standing
This only happened on this model.
After canceling in the console:
![scr3](https://user-images.githubusercontent.com/65903670/134354845-17ca0b3f-107e-40d8-9658-f502a8b97266.JPG)

**Comment by xPaw** [comment]
There is a limitation with gltf where too big models won't fit into one file, so it's being split into many small ones. It's not ideal, but from what I'm seeing it's not stuck, it's just taking a long time to export.

**Comment by faust-hub** [comment]
You're right. This is not a bug, but a very bad model. I waited a very long time to unpack it and got the result of an incredibly large size. The VRF works great. Valve sucks

**Comment by Teajai2** [comment]
I attempted to decompile the Half-Life Alyx zombie and leave the process running overnight. When I woke up, my computer was incredibly slow, so I restarted my PC and I could not get it to boot it up again.

As it would turn out, my hard drive broke, and I had to literally get a new one in order to continue using my computer.
