### ISSUE TITLE
Implement Decompiled Valve File Formats

### ISSUE THREAD

**Issue by SinZ163** [SteamDatabase/ValveResourceFormat#38]
The following formats need to be implemented to add functionality to Decompiler:
- [ ] **VMDL** using [schema text](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl)
- [x] **VPCF** using [KeyValues3](https://github.com/MNoya/DotaCraft/blob/dd84aeb405b45cd3871f6d1c462d460bc17fb250/content/dota_addons/dotacraft/particles/buildinghelper/square_sprite.vpcf)  now, previously used [schema text](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/particles/auras/aura5.vpcf)
- [ ] **VTEX** using [KeyValues2_noids](https://github.com/MNoya/DotaCraft/blob/6f622cb12229556b904205966bd4937b3f04365a/content/dota_addons/dotacraft/materials/demon_rune.vtex)
- [ ] **VMAT** using [KeyValues](https://github.com/MNoya/DotaCraft/blob/6c3ab30af52541d5433da1459ea9abf444cb7aae/content/dota_addons/dotacraft/materials/hills_of_glory.vmat)
- [ ] **VMAP** using [DMX encoding binary 9](https://github.com/MNoya/DotaCraft/blob/24e2685739627fa55385db97fa02a19f5389837d/content/dota_addons/dotacraft/maps/2_hillsofglory.vmap)
- [ ] **VSNDEVTS** using [KeyValues](https://github.com/MNoya/DotaCraft/blob/9c586aaf2d5a110948581201b8d5f89be15ccf99/content/dota_addons/dotacraft/sounds/wc3/building_placement.mp3) (Note in compiled form, older files are KV(1) inside the NTRO Wrapping, but newer files are KV3. Still always KV(1) in decompiled layout though)
- [ ] **VSNDSTCK** potentially using KeyValues? (It looks the same as VSNDEVTS in compiled form)

**Comment by xPaw** [comment]
Closing in favor of separate issues.
