### ISSUE TITLE
Vmorf (shape keys) channels export with models

### ISSUE THREAD

**Issue by DenK302** [SteamDatabase/ValveResourceFormat#389]
### Is your feature request related to a problem? Please describe.

Vmorf (shape keys) channels are lost with export in gltf/glb

### Describe the solution you'd like

I can help with .dmx models, where morph channels works fine (like stereo morphs)

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/blob/master/library/source2/data_blocks/mrph_block.py This can be used as a reference on how to interpret morf data.
