### ISSUE TITLE
Decompiler.exe and Windows 7

### ISSUE THREAD

**Issue by muk-as** [SteamDatabase/ValveResourceFormat#390]
### Describe the bug

https://github.com/SteamDatabase/ValveResourceFormat/actions/runs/1408195584
0.1.10.838 - last working version on Windows 7 X64

all other versions after 0.1.10.838 got error about missing api-ms-win-core-winrt-l1-1-0.dll

P.S. VRF.exe last versions is working

### What Valve game does this happen in

All

### Reference file in a Source 2 game

All

### Expected behavior

All

### What version of VRF are you using? On what platform?

Decompiler.exe after 0.1.10.838 on Windows 7 x64

**Comment by xPaw** [comment]
Windows 7 is EOL.

You can try figuring out why NET 6 doesn't work on it (e.g. compiling yourself), but nothing extra will be done in VRF.
