### ISSUE TITLE
Accessor[6] Format: value SharpGLTF.Memory.AttributeFormat is invalid.

### ISSUE THREAD

**Issue by TheBoxTrot** [SteamDatabase/ValveResourceFormat#398]
### Describe the bug

bug when trying to export a model I'm assuming with larger models 
Accessor[6] Format: value SharpGLTF.Memory.AttributeFormat is invalid.

### What Valve game does this happen in

The Lab

### Reference file in a Source 2 game

aperture/models/start_room_model.vmdl_c

### Expected behavior

to have the model exported 

### What version of VRF are you using? On what platform?

0.2.0.864 Windows 10

**Comment by xPaw** [comment]
This model has BLENDWEIGHT with two components (R16G16_UNORM), but gltf expects vec4 for weights.

I've made it skip them for now so it exports, but weights are lost.
