### ISSUE TITLE
Crash when decompilling models or material files

### ISSUE THREAD

**Issue by mundusnine** [SteamDatabase/ValveResourceFormat#404]
### Describe the bug

When trying to decompile and export, VRF just crashes. It doesn't crash at a specific file. VRF doesn't give a crash file or crash output.

### What Valve game does this happen in

Aperture Desk Job

### Reference file in a Source 2 game

![image](https://user-images.githubusercontent.com/29337013/158206943-c7863064-0838-4947-9776-6b4b1569181b.png)

### Expected behavior

No crashing.

### What version of VRF are you using? On what platform?

Windows v0.2.0.864

**Comment by xPaw** [comment]
I can't reproduce (it works).

Are you saying it just closes? Perhaps check your Event Viewer for any errors.

**Comment by mundusnine** [comment]
> I can't reproduce (it works).
> 
> Are you saying it just closes? Perhaps check your Event Viewer for any errors.

Indeed, a crash implies that the application just closes. For the Event Viewer you mean the integrated console ?: 
![image](https://user-images.githubusercontent.com/29337013/159050927-117a2029-60bd-42a0-8919-2f49ebdf6e79.png)


If so as it crashes and on restart of the application, the console output gets flushed.

**Comment by xPaw** [comment]
No, I mean the windows event viewer.

**Comment by mundusnine** [comment]
Will have a look and get back to you.

**Comment by mundusnine** [comment]
> No, I mean the windows event viewer.

Here are the events logs saved.

It seems like it related to a .NET 6.0.1 runtime error.
[Uploading vrf_crash.zip…]()

**Comment by xPaw** [comment]
> The process was terminated due to an internal error in the .NET Runtime.at IP 00007FF7455BC0E9 (00007FF745370000) with exit code c0000005.

Unfortunately there's very little actionable information to help you here. The runtime is crashing in native code, thus we don't get any managed code exception and there's no information as to what could be causing this.
