### ISSUE TITLE
Help ;3

### ISSUE THREAD

**Issue by Lgazana** [SteamDatabase/ValveResourceFormat#414]
### Describe the bug

Hey, guys. Sorry for bothering you, but I can't join the discord because my steam account is restricted, and I was hoping you could help me with a simple question.
I'd like to extract specific files from Dota 2's "pak01 dir" using the command line "cmd" and the program VRF.exe but it doesn't appear to be working. I must be doing something wrong.
This is what I typed into cmd, and when I press Enter, vrf.exe opens the "pak01 dir" but doesn't extract anything.

VRF "D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk" "D:\SomeFolder\particles\dire_fx\dire_lava_falling_rocks_sparks.vpcf" "D:\SomeFolder\particles\dire_fx\dire_lfr_sparks_13sec.vpcf" "D:\SomeFolder\particles\dire_fx\dire_lfr_sparks_19sec.vpcf"

What I hope to gain from this is the ability to use cmd and vrf.exe to automatically extract thousands of SPECIFIC files to a SPECIFIC folder.

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

.

### Expected behavior

.

### What version of VRF are you using? On what platform?

.

**Comment by xPaw** [comment]
Use decompiler.exe

VRF.exe is a GUI application.

**Comment by Lgazana** [comment]
Thank you very much! and apologies But, if you don't mind, could you please tell me whats the correct "cmd" command I should use with decompiler.exe to extract three specific files from Dota 2's "pak01 dir"? I've tried this and a few others, but I'm a complete noob at this and it's not working.

decompiler.exe "D:\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk" "D:\SomeFolder\particles\dire_fx\dire_lava_falling_rocks_sparks.vpcf" "D:\SomeFolder\particles\dire_fx\dire_lfr_sparks_13sec.vpcf" "D:\SomeFolder\particles\dire_fx\dire_lfr_sparks_19sec.vpcf"

I would appreciate even the smallest example you could provide so that I could use and learn from it.
