### ISSUE TITLE
Support for Unity3D

### ISSUE THREAD

**Issue by in0finite** [SteamDatabase/ValveResourceFormat#418]
### Is your feature request related to a problem? Please describe.

Have you considered making the code compatible with Unity3D engine ?

I see that recently you migrated to .NET 6 which would definitely break the support for Unity3D, since it runs on .NET 4.7 (Mono).

It would definitely be useful to use this library in Unity3D, for various reasons. For example, someone could try to import Source 2 game assets into Unity3D to do various stuff (editing map, applying better graphics, etc).

Speaking of which, why do you actually use your own rendering and GUI, when you could easily do it in a modern game engine such as Unity3D ?

**Comment by xPaw** [comment]
No.
