### ISSUE TITLE
Vmap_c not decompile

### ISSUE THREAD

**Issue by PlushaCat** [SteamDatabase/ValveResourceFormat#423]
### Describe the bug

why vmap_c  not decompile? 
![image](https://user-images.githubusercontent.com/104760630/166214580-553b2ae6-f5dc-4bad-99d6-d657efcec1c3.png)

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

custom game in dota 2 map

### Expected behavior

decompile file

### What version of VRF are you using? On what platform?

0.2.1.963

**Comment by xPaw** [comment]
vmap doesn't have any data, you want to decompile vwrld or separate meshes.

**Comment by PlushaCat** [comment]
can I use other data files to create a vmap?

**Comment by kristiker** [comment]
you can use the entity lump data to get entities back, but you'll need to write vents->vmap converter yourself.
