### ISSUE TITLE
Export images in one go

### ISSUE THREAD

**Issue by bert-w** [SteamDatabase/ValveResourceFormat#444]
### Is your feature request related to a problem? Please describe.

I have a large list of `.vtex_c` files which I want to export to PNG. The GUI only seems to support exporting one by one which takes a long while. Any chance you can add some sort of "Export all" feature?

### Describe the solution you'd like

"Export all to PNG" feature for opened `.vtex_c` files.

**Comment by bert-w** [comment]
I found a solution using the cli decompiler:

```shell
Decompiler.exe -i yourinputpath -o youroutputpath --recursive -d
``` 
However there seems to be something wrong with the parsing the output path. It will only write results to my `C:\` root (Windows 10).

**Comment by kristiker** [comment]
> However there seems to be something wrong with the parsing the output path. It will only write results to my C:\ root (Windows 10).

Fixed in latest unstable.

> Export images in one go

Most Valve games have textures in the vpks where the GUI allows you to export whole folders.

**Comment by xPaw** [comment]
CLI can also decompile from vpk recursively, check the option to filter by extension.
