### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by NanoNM** [SteamDatabase/ValveResourceFormat#458]
### Describe the bug

when I dump dota2 loadingscreen AccessViolationException happed

cmd :
![image](https://user-images.githubusercontent.com/42882446/204975993-3aa8bae3-2077-41ff-a016-ac5d40af9aa4.png)

Exception:
![image](https://user-images.githubusercontent.com/42882446/204975736-6e03c4b5-9c4f-422e-8e0f-340b62661c43.png)

### What Valve game does this happen in

Dota2

### Reference file in a Source 2 game

D:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk

panorama\images\loadingscreens

### Expected behavior

Unpack and decompile all loaded images

### What version of VRF are you using? On what platform?

Windows 0.2.2.1057

**Comment by xPaw** [comment]
This is fixed in unstable

**Comment by NanoNM** [comment]
thx for response
