### ISSUE TITLE
"Upload" tests on appveyor builds

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#46]
So that they show up under "tests" tab properly.

**Comment by yaakov-h** [comment]
You probably have to use AppVeyor's binary:

> NUnit 3.x
> 
> To run NUnit tests with reporting test results to AppVeyor use command:
> 
> `nunit3-console <assembly> [options] --result=myresults.xml;format=AppVeyor`

**Comment by xPaw** [comment]
291b9dd498f2e61f9e26981aef691166c23a80a4

It was enough to save test results to a file without uploading them, and appveyor picks it up.
