### ISSUE TITLE
Windows-1252 is treated as UTF-8

### ISSUE THREAD

**Issue by SamyHasRoot** [SteamDatabase/ValveResourceFormat#466]
### Describe the bug

When decompiling HL:A SoundEvents, Windows-1252 encoded dialog is incorrectly decoded as if it where UTF-8.
This results in `…` (ellipsis) and `—` (em dash) and being replaced with U+FFFD.

### What Valve game does this happen in

HL:A

### Reference file in a Source 2 game

`soundevents/soundevents_vo_alyx.vsndevts_c` in `pak01_dir.vpk` in `/path/to/h:la/game/hlvr`

### Expected behavior

That ether the original bytes of the string are kept or that the strings in `stringArray` are read using correct encoding.

### What version of VRF are you using? On what platform?

Commit 09787d0 on Linux

**Comment by SamyHasRoot** [comment]
Interesting, i assumed it was Windows-1252 as the encoding matched. Does KV3 have a specific string encoding? Assuming it has and that it isn't utf-8, or that it hasn't, why decode it as utf-8?

Should i update the issue's title? (first time doing this)

**Comment by xPaw** [comment]
KV3 (file) doesn't specify how the strings are encoded. It's has null terminated strings (in this particular file in a table of strings).

We can't just take raw bytes and magically turn it into a string without some encoding.

**Comment by SamyHasRoot** [comment]
Then why are they being turned into strings in the first place? For file output couldn't we just write the original bytes (completely bypassing c# strings) and let the user decide how to interpret it?
If it happens to be utf-8 encoded, there should be no difference.
But if it is some other encoding, you would get *some* data instead of just U+FFFD.

**Comment by xPaw** [comment]
Because it's a string table, and just dumping bytes into a file is not the first use case. As I said before, even Valve's own tool dumps a U+FFFD there.

**Comment by SamyHasRoot** [comment]
You make a persuasive argument.
