### ISSUE TITLE
Verify VPK signatures

### ISSUE THREAD

**Issue by DoctorMcKay** [SteamDatabase/ValveResourceFormat#47]
VPKs can be signed (signed VPKs must be multi-file).

I've attached an example signed VPK and the corresponding public key.

[firepowered.publickey.vdf](https://github.com/SteamDatabase/ValveResourceFormat/files/125295/firepowered.publickey.vdf.txt)
[High Tech Bow.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/125301/High.Tech.Bow.zip)

You can create keys, verify signatures, and create signed VPKs using vpk.exe.

- `vpk generate_keypair example`
- `vpk -k example.publickey.vdf checksig modfile_dir.vpk`
- `vpk -M -k example.publickey.vdf -K example.privatekey.vdf inputfile`

**Comment by xPaw** [comment]
I've added code to read the remaining VPK v2 sections, and public key along with signature are exposed in the API now. It's a matter of adding helper methods to verify them now (or leave it up to the consumer?)

**Comment by xPaw** [comment]
c3d99f886e5f4109cf7bb7c8b93fea0690f208f3
