### ISSUE TITLE
Physics model export

### ISSUE THREAD

**Issue by DrinklyDram** [SteamDatabase/ValveResourceFormat#480]
### Is your feature request related to a problem? Please describe.

It's not possible to export the physics model, which is very important in some cases.

### Describe the solution you'd like

I'd like to have an **_Export physics model_** button in the **_Export_** tab.

![image](https://user-images.githubusercontent.com/40040054/207082816-cc5f936b-d1cc-48b4-b439-6d1d2c324312.png)

### Describe alternatives you've considered

Perhaps the physics model can also be exported along with the default mesh by default. Thanks!

**Comment by xPaw** [comment]
Can you give an example of how you would expect it to be exported? Are you talking about vphys files?

glTF spec doesn't support physics.

**Comment by DrinklyDram** [comment]
As a separate glTF mesh. Like when decompiling a source 1 model, we get two meshes: one is the actual mesh and the other one is collision.

**Comment by lewa-j** [comment]
But what about shapes other than mesh? Spheres, capsules, hulls, etc.

**Comment by kristiker** [comment]
The recently added vmdl (not glTF) extract generates dmx collision hulls/meshes.

**Comment by xPaw** [comment]
Exporting vphys to gltf is now available in dev build.
