### ISSUE TITLE
Write up format documentation

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#5]
I think using github wiki is best suited for this. Anyone want to help with this?

**Comment by SinZ163** [comment]
Sure, why not

**Comment by SinZ163** [comment]
Documentation currently up to date with repository

**Comment by xPaw** [comment]
Would be nice to expand our readme now to explain different projects in the repo (decompiler, gui, library itself, tests?)

**Comment by SinZ163** [comment]
and in regards to the wiki, having a write up of the DATA formats such as Panorama and the DATA_ENCODING's possible (VKV3)

**Comment by EXayer** [comment]
Pls Help me, tell how to launch decompiler, I don't understand there isn't .exe. What file should I launch or I need some program?
