### ISSUE TITLE
Modelviewer tasks

### ISSUE THREAD

**Issue by Marlamin** [SteamDatabase/ValveResourceFormat#50]
- [x] Proper directory search possibly w/ user settings
- [x] Alpha channels & blending
- [x] Mesh preview in vmdl
- [x] Support mipmaps, textures are already loaded in
- [x] TexCoord2 support
- [x] Research g_tColor1/g_tColor2
- [ ] Bone weights & indices
- [ ] Animations!
- [x] Research vTintColor & implement in shaders
- [ ] Fix default camera positioning
- [ ] Fix camera to be able to look straight down/up
- [x] Embed error texture
- [x] VPK support
- [x] Load different shader files based on the shader name as seen in the vmat.
- [x] Extend the shader source manipulator to support #includes.
- [x] Change the shader source manipulator to take default values for #defines from shader includes.

Let me know if I'm missing something important!

**Comment by xPaw** [comment]
- [ ] Antialiasing would be nice to have

**Comment by SinZ163** [comment]
Slightly less trivial, as models are allowed multiple meshes, so it either needs to be able to switch between them, or just choose one of them.

**Comment by xPaw** [comment]
Or just render them all at once :)
That should be just binding all vertices from all meshes, and combining drawcalls.

**Comment by SinZ163** [comment]
With the camera, might be a good idea to add a keybind to teleport the camera back to default so you don't get lost in the world of black

**Comment by Perryvw** [comment]
I would like to add some points that need to be done.
- Load different shader files based on the shader name as seen in the vmat.
- Extend the shader source manipulator to support #includes.
- Change the shader source manipulator to take default values for #defines from shader includes.

**Comment by xPaw** [comment]
Couple things need fixing for #64:
- [ ] Support loading multiple meshes (from a single model)
- [ ] Support rendering multiple `m_sceneObjects`
