### ISSUE TITLE
Incorrect mesh normals on GLTF export

### ISSUE THREAD

**Issue by DarkBlade909** [SteamDatabase/ValveResourceFormat#523]
### Describe the bug

Mesh normals exported to GLTF and imported into Blender have incorrect rotation.

### What Valve game does this happen in

Half-Life: Alyx

### Reference file in a Source 2 game

models/props_combine/combine_battery/combine_battery_large.vmdl

### Expected behavior

Current result on import:
![image](https://user-images.githubusercontent.com/52094720/227574280-201c5bcd-b01b-4a56-b0dc-e591e1cf83ec.png)
Expected:
![image](https://user-images.githubusercontent.com/52094720/227574332-fc218f9e-0f2a-4726-aad2-2e9ca210acf2.png)

Steps to reach expected result:
1. Go into Edit Mode
2. Press A to Select All
3. Alt+N -> Flip
4. Check "Custom Normals Only" in the bottom left
5. Alt+N -> Rotate
6. Press Z, type 180, enter
7. Alt+N -> Rotate
8. Press X, type -90, enter 

### What version of VRF are you using? On what platform?

v0.3.1 on Windows 10

**Comment by xPaw** [comment]
Should be fixed by 56a52111f1a1933c15516eb40b6249c020f24106, just need to verify against different games.
