### ISSUE TITLE
Features bytes section of vcs files doesn't correctly prints version specific bytes

### ISSUE THREAD

**Issue by GAMMACASE** [SteamDatabase/ValveResourceFormat#529]
### Describe the bug

This code suggests that theses 6 additional bytes are version 65 specific, where in reality they are also present in 66 version of the file https://github.com/SteamDatabase/ValveResourceFormat/blob/271c5f080bacdc51601c5d20a77afa36b25bd6f4/ValveResourceFormat/CompiledShader/ShaderDataBlocks.cs#L813-L816
it also parses all the files by default starting from version 65 with that scheme https://github.com/SteamDatabase/ValveResourceFormat/blob/271c5f080bacdc51601c5d20a77afa36b25bd6f4/ValveResourceFormat/CompiledShader/ShaderDataBlocks.cs#L687-L690
as a proof that 66 version has these additional bytes, here's the hex view of the file (on the right) and the VRF output of the same location (on the left).
![image](https://user-images.githubusercontent.com/31375974/227759683-b4fa40a8-1c9b-4903-b93c-3ca73dc4d337.png)

### What Valve game does this happen in

CS2

### Reference file in a Source 2 game

[cables_pc_50_features.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/11070947/cables_pc_50_features.zip)
path: gameroot/shaders/vfx/

### Expected behavior

Feature bytes section should correctly display the additional 6 bytes on vcs files with version that are higher than 65.

### What version of VRF are you using? On what platform?

0.3.1.1553 Windows

**Comment by kristiker** [comment]
Ok it's the byte detail viewer. That method is behind the main reader in a buch of places due to having to maintain duplicated code. It is meant for debugging really.

**Comment by GAMMACASE** [comment]
That byte viewer is actually quite useful to analyze the actual byte layout of the binary without diving into the code much
