### ISSUE TITLE
Execution Engine Exception

### ISSUE THREAD

**Issue by EthanCGamer** [SteamDatabase/ValveResourceFormat#53]
An unhandled exception of type 'System.ExecutionEngineException' occurred in ValveResourceFormat.dll

System.ExecutionEngineException was unhandled
  HResult=-2146233082
  Message=Exception of type 'System.ExecutionEngineException' was thrown.
  InnerException: 

That's all VS 2015 gave me, it brought me to this:
![2016-03-02 1](https://cloud.githubusercontent.com/assets/7083279/13475139/c853cfa2-e086-11e5-87db-73823489aca6.png)
I was trying to decompile the new SteamVR data, and it crashed at 

> [23498/30074] C:\Users\ethan\SteamVR\depots\323911\997500\vr\models\characters\npc\materials\engineer_shirt_color_psd_40458d3.vtex_c
Parsed in 0ms

**Comment by xPaw** [comment]
That's very unlikely to be an error in our code.

> The exception that is thrown when there is an internal error in the execution engine of the common language runtime. This class cannot be inherited.

> In some cases, an application that targets the .NET Framework may throw an ExecutionEngineException exception during garbage collection when an application or the system on which it is running is under a heavy load. In this case, To work around this issue, you can disable concurrent garbage collection by modifying the application's configuration file. For more information, see How to: Disable Concurrent Garbage Collection.
