### ISSUE TITLE
Skybox models not shown properly due to camera's depth clearing

### ISSUE THREAD

**Issue by in0finite** [SteamDatabase/ValveResourceFormat#557]
### Describe the bug

When looking at some skybox models while they are placed in front of map's models, the skybox models are only partially visible, due to their depth buffer being cleared before rendering the main camera. Also, they sometimes seem to follow the camera.

These artifacts are visible from normal map locations, such as T-spawn on Dust 2.

Just by moving the camera left-right on T-spawn, while looking toward B site, you can see how a skybox object is moving left-right with you.

Image from bottom-mid when elevated:
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/22325861/66cc7981-934c-45dd-bd1b-9f9498cf3613)

Image from T-spawn:
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/22325861/e88f0866-0fde-413d-9832-9e42f626e2a1)

Image from T-spawn, when moved a bit to the left:
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/22325861/fe92401a-544f-4bb7-93e6-902973aa4a5a)

### What game does this happen in

CS2

### Reference file in a Source 2 game

de_dust2

### Expected behavior

The skybox model should be rendered in front of other map's models normally.

### What version of VRF are you using? On what platform?

v0.3.2.0+cf26fc5c6a32942ca1e5be623dbcd09eb3553608

**Comment by xPaw** [comment]
Source engine also draws skybox first and then clears the depth buffer. It looks wonky in VRF because we don't hide geometry by visibility like the Source engine does, so stuff ends up drawing on top of the skybox when it shouldn't.
