### ISSUE TITLE
Decompile CS2 maps

### ISSUE THREAD

**Issue by JimmyWoodhouse** [SteamDatabase/ValveResourceFormat#567]
### Is your feature request related to a problem? Please describe.

It would be great to be able to decompile a CS2 map from a VPK to a VMAP + the assets.
There is currently no tool with the ability to do this it seems, and it would be very useful.
It looks like this PR took a stab at starting it, but has been left idle for a while
https://github.com/SteamDatabase/ValveResourceFormat/pull/539

Currently, in v0.4.0, attempting to decompile a vpk results in various issues. de_nuke throws an error, whereas de_mirage crashes VRF.

Thanks!

### Describe the solution you'd like

Decompile a CS2 vmap from a compiled vpk.
Exporting the vmap in a /maps folder, the materials in their correct folder structure inside of the /materials/, and so on, would be very beneficial.

**Comment by kristiker** [comment]
Try this version of VRF-GUI out:
https://github.com/SteamDatabase/ValveResourceFormat/actions/runs/5426082634

Right click and Decompile the vmap_c to your content/maps folder.

**Comment by JimmyWoodhouse** [comment]
This is brilliant, thanks a lot!

It works really well on the whole. It creates a few artefacts, but not many at all

![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/17306057/a5656734-6588-40d9-8edf-90070842337d)

**Comment by JimmyWoodhouse** [comment]
It looks like there are a few things missed, for example, it doesn't seem to export meshes with tool textures properly. If they are bound to an entity, they show in Entity Report, but nothing shows visually (with Show tool materials enabled)

**Comment by kristiker** [comment]
Not exporting physics meshes at the moment, which is what some of the tool textures get converted to (e.g func_buyzone, can be viewed in VRF). No map physics either. Mesh decompiling is also at an early stage, so some mesh chunks are omitted. I forgot about entities though, but since those don't have culing data embedded into them you can extract the `entities` folder untouched on the /game/ side and maybe that will make some brush entities show up.

**Comment by JimmyWoodhouse** [comment]
Ah this makes sense, thanks for letting me know. Do you have an approximate ETA at all?
Appreciate it!

**Comment by kristiker** [comment]
Latest artifact can export mesh-based map physics. Try by right clicking on the Editable World Physics > Selected entity > Convert to editable mesh.

 <img src="https://cdn.discordapp.com/attachments/775429805469597768/1127918538145931354/image.png">

**Comment by JimmyWoodhouse** [comment]
Awesome, thanks, I'll have to check it out!
Annoyingly, a map can't be decompiled twice due to an exception, here's an example:
Failed to extract 'de_nuke.vmap_c': An item with the same key has already been added. Key: $417707814

**Comment by kristiker** [comment]
That has been fixed. Most improvements from now on are going to be with the model decompiler

**Comment by xPaw** [comment]
Decompiler was merged, create new issues with specific problems in it.
