### ISSUE TITLE
Fix animation bbox calculations in CS2 player models

### ISSUE THREAD

**Issue by kristiker** [SteamDatabase/ValveResourceFormat#571]
### Describe the bug

I think the game doesn't bother with recalculations and instead uses the largest one. I used r_showsceneobjectbounds a while ago on Aperture Desk and they were large, nonchanging. Need to verify again.

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

de_mirage.vwrld - playerspawns are assigned the wrong envmap

### Expected behavior

Selecting the model should show accurate bounds.

### What version of VRF are you using? On what platform?

0.4.0

**Comment by xPaw** [comment]
Fixed in ad10461f8ec0dcd9ecd75afe272bb936b41cf953
