### ISSUE TITLE
Support VPKs

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#6]

**Comment by SinZ163** [comment]
@Penguinwizzard's VPK lib in C# will probably be good for this. https://github.com/ModDota/ModDotaClient2/blob/master/Helper/ModDotaHelper/VPK.cs
Wasn't completed in that repo though.

**Comment by xPaw** [comment]
Rick has a C# implementation: http://svn.gib.me/public/valve/trunk/

**Comment by xPaw** [comment]
VPK reading and dumping is supported by the library now, just need to add an option to specify files in decompiler.

**Comment by SinZ163** [comment]
VPK's on the file system are fully supported now, but multipart VPK's inside other VPK's (Potentially exists, but none in dota) aren't. Probably good enough to close though.
