### ISSUE TITLE
Allow exporting "raw" PNG images from vtex files via CLI Decompiler

### ISSUE THREAD

**Issue by chescos** [SteamDatabase/ValveResourceFormat#600]
When exporting a `vtex` file to `png` using the `CLI Decompiler` via:

```
.\Decompiler.exe --input input.vtex_c --output output.png
```

The resulting file is different from using the `GUI Viewer` and exporting the same file via the `Export as is` or ` Decompile & export` option.

I would love to be able to generate the same result from the CLI as with the GUI.

My use case is to compute CDN hashes for CS:GO/CS2 items. For this, you need the "original/raw" PNG image file and compute a SHA1 hash of it. The GUI generates the correct file for this, the CLI doesn't.

**Comment by xPaw** [comment]
Different how?

**Comment by chescos** [comment]
The file size is different (smaller) via the CLI, thus resulting in a different SHA1 hash of the file. I assume there is some compression used via the CLI?

**Comment by xPaw** [comment]
Can't confirm:
```
cb807167e46d6ccba13617cc0814778f8dfd51cae9ed11a0cde1a5f1886a0c51  lattice01_color_tga_30ddcc07.vtex_c
dd59abdd7a6886562f1a6ffaf843dc5d226e5c21b51918f20fe2a56c12bb5fb7  gui.png
dd59abdd7a6886562f1a6ffaf843dc5d226e5c21b51918f20fe2a56c12bb5fb7  cli.png
```

You'll need to be more specific.

**Comment by chescos** [comment]
Sorry, my bad. Just double-checked and noticed that I used an exported PNG from the CS:GO pak01 for comparison instead of an exported PNG from the CS2 pak01. The results via CLI and GUI are indeed the same, so no issue there.

Do you happen to know whether Valve just changed the PNG input files in CS2, or does this library not restore the "original" PNG files that Valve used as inputs for the vtex files?

**Comment by xPaw** [comment]
https://github.com/SteamDatabase/ValveResourceFormat/blob/master/ValveResourceFormat/Resource/ResourceTypes/Texture.cs#L375

Entire depends on its format. We output pngs but that doesn't mean the vtex had png data stored (view data tab in gui).

**Comment by chescos** [comment]
Thanks! The format seems to be `VTEX_FORMAT_PNG_RGBA8888`. Does VRF restore the original input file in that case, or is there some decoding/compression/encoding happening that results in a different output file?

**Comment by xPaw** [comment]
The image is re-encoded through Skia, which does seem wasteful when it's being directly extracted, I created #601 to tackle this.

**Comment by chescos** [comment]
Got it, thanks for confirming. And thanks for all your awesome work in space!
