### ISSUE TITLE
Help with vsndevts

### ISSUE THREAD

**Issue by ghost** [SteamDatabase/ValveResourceFormat#76]
Hello guys, i spent about few month in google in searching answers on my question, but failed.
I can't find any information about syntax vsndevts file before compiling.
After dozens of experiments i successfully compiled vsndevts_c from vsndevts, and my compiled file worked on dota 2 reborn.

Before compilation
http://pastebin.com/7MH8cxUs

After(only DATA block) 
http://pastebin.com/6PjVhrzY

But i anyway want to find documentation which explain how correctly write vsndetvts before compiling, i don't understand what means this "operator_stacks", "update_stack", "reference_operator", "operator"        "sos_reference_stack" and other. And i want to understand what this words means.

**Comment by SinZ163** [comment]
I don't think valve ever documented it as such, but the [community](https://github.com/MNoya/DotaCraft/blob/9c586aaf2d5a110948581201b8d5f89be15ccf99/content/dota_addons/dotacraft/soundevents/wc3_sounds.vsndevts) went off how valve used them in some of their gamemodes (frostivus, holdout and Colosseum).

And currently vsndevts can be in both KV1 format and KV3, though I've never seen any KV3 ones with content files to match.
