### ISSUE TITLE
Exporting textured models

### ISSUE THREAD

**Issue by Jademalo** [SteamDatabase/ValveResourceFormat#95]
In the Robot Repair demo in The Lab, you use an awesome wand controller model to interact with everything. Since SteamVR has the ability to customise controller model, I thought it would be great to try and use this model.

After spending a few hours on this, I've hit a brick wall. I'm able to successfully extract the .obj and the related textures, but there's no UV data in the exported .obj
When exploring the pak01_dir.vpk and selecting the model (aperture/models/vrcontroller.vmesh_c), it correctly displays with texturing etc, so I know the model itself isn't broken and the UV data is there somewhere.

If I'm correct, the UV map for a material is stored in the vmat somewhere. When trying to decompile vr_controller.vmat_c, I get the error "-- (I don't know how to dump this resource type)", though according to the readme it should be possible to dump this. I'm able to open it in the GUI and view it without any issue.

Is there no way to export both the model and UV data into the .obj format so it can be used with SteamVR?
Ideally when exporting a .obj loaded from a vpk it should include the UV data  so that textures can be applied.

Thanks

**Comment by SinZ163** [comment]
Dump the corresponding `vtex_c` that goes with the vmat.

`vmat_c` only stores metadata and references, while everything interesting is in the `vtex_c`

**Comment by Jademalo** [comment]
I'm able to dump that, and I'm left with the .obj and the .png of the model and the texture. However there seems to be no UV or texture coordinate information in the obj, so no matter what I do I can't get the model to be textured.

It's the UV maps I really want. It's also a bit weird since it seems to be 6 separate models combined in the .obj too, with 6 separate texture files.

**Comment by xPaw** [comment]
Yeah so TEXCOORD and NORMAL aren't being dumped to obj file.
I looked at it real quick, but it's in different type compared to position.

right here: https://github.com/SteamDatabase/ValveResourceFormat/blob/f4082de9979ffd14d8dd4e8e6d081ae0efd3650e/GUI/MainForm.cs#L875

**Comment by Jademalo** [comment]
Alright, thanks for the clarification!

Would it be substantial work to implement it? If not then I'll close this and submit a proper enhancement request for it, but if it's a ton of work and not worth the effort I'll just close it.

Thanks!

**Comment by Marlamin** [comment]
That commit should add texture coordinates. It should work fine on single mesh+texture models. However, models with multiple meshes (and as such multiple textures) aren't supported yet and will need additions of groups and material files which is a lot more work.

**Comment by Jademalo** [comment]
Thanks, I'll (attempt to) compile that now and get back to you!

I've got a rough knowledge of how the .obj format is put together, would this commit put out enough info for a multiple mesh model to be able to manually write the groups and material files?

**Comment by Marlamin** [comment]
Unsure. It's been a few years since I looked at how Valve builds up their model files so I'd have to delve in deeper. But it is possible everything is in a proper enough order to manually added those groups/material references, yeah.

**Comment by Jademalo** [comment]
Alright, thanks! I'll let you know how I get on.

**Comment by Jademalo** [comment]
Bad news unfortunately, something seems messed up for models with multiple meshes. Not exactly sure what, but all of the textures are all over the place. 
I should have properly assigned both groups and materials, but the texture data is extremely glitchy. I believe there's an error somewhere in the export, since there are a few vt values that are showing NaN. I believe this is causing errors, and a single wrong UV will totally throw the order for the rest of them.

https://www.dropbox.com/s/o9wkeodkoo2pzdb/vr_controller_vive_1_5.zip?dl=0

That folder has the raw exported obj, the texture files, and the object after I added groups and texture maps. No idea why the NaN error is happening though.

**Comment by Marlamin** [comment]
Hmm, was afraid of that. Will look into it.

Are you just looking for the Vive controller model? I think they have the same version included in SteamVR somewhere already as an obj.

**Comment by Jademalo** [comment]
It's not the standard model, there are a few versions of that I've been able to find.

In Robot Repair, one of the demos in The Lab, you have a really awesome aperture themed controller - https://cdn.discordapp.com/attachments/340633160893333505/401554024681177108/unknown.png

If you download The Lab for free, the model is in "The Lab\RobotRepair\vr\pak01_dir.vpk"
Within the vpk, going to "\aperture\models\vr_controller.vmesh_c" should load it. The viewer GUI loads it no problem, and it's not the worlds most complicated model.

This model doesn't exist outside of Robot Repair, but it would be absolutely perfect to use as a SteamVR custom controller.

**Comment by Marlamin** [comment]
Will check it out if I can find some time this weekend. Thanks!

**Comment by Jademalo** [comment]
Awesome, thank you!

**Comment by Marlamin** [comment]
Those NaNs should be fixed now. Other stuff still needs doing.

**Comment by Jademalo** [comment]
Holy crap, extreme progress!
Looks like the image needs to be flipped vertically, but the mapping is correct when that is done.
Spent a bit cleaning up the materials and groups, and it's a fully textured model now!

Obviously I'm having to guess with materials, and I've not got a clue how the normal maps work, but it's insanely close!

Thanks a ton!

**Comment by xPaw** [comment]
Normal maps (vn) is a separate attribute, and it's not being written to obj yet.

**Comment by Marlamin** [comment]
Latest commit should flip the texcoord the right way (I think). Normals still TODO.

**Comment by Marlamin** [comment]
Normals are exported as well now, but only those of a specific format. _Should_ work for the aperture VR controller, but might fail on other models.

**Comment by Jademalo** [comment]
Looks like that all works correctly, not 100% sure though. Textures are the correct orientation now though definitely.

**Comment by Marlamin** [comment]
With that latest commit there should theoretically be support for models with multiple groups/textures. It will output an obj file with groups (I just noticed they should be objects of one group instead of multiple groups but that is for a future date) and a mtl file. However, the textures themselves still have to be manually extracted for now. Hopefully we can find a solution for that at one point.

Here's GLaDOS from the Robot Repair demo (imported in Blender) with the only manual work being extracting textures. 

![image](https://user-images.githubusercontent.com/50212/34911389-0170ce86-f8ca-11e7-9e7d-4d43a5ba8317.png)

**Comment by Jademalo** [comment]
Wow, the work you've done on this so quickly is absolutely insane!

Just built the latest revision, and while it builds the obj correctly and what looks to be a compatible .mtl file, it seems like there's an issue with texture names.

The .mtl file is showing things like this;
`newmtl vr_controller
illum 2
map_Ka vr_controller.png
map_Kd vr_controller.png`
However the dumped textures are named;
`vr_controller_color_psd_9db6e26.png
vr_controller_normal_psd_e314df24.png`

There's also a bit of a weird thing with the export of the controller specifically - The vr_controller_sensor group actually uses the vr_controller colour texture, it's a purple splodge in the corner, as well as a separate file for the gloss map. The export for whatever reason isn't creating that material correctly.



There is one more issue with regards to materials, but I've got no idea if there's a particularly easy way to fix this.
After studying the controllers in Robot Repair closely, I've got a much better idea of what they should look like, compared to how they're looking when exported. The white areas are very glossy, the terracotta back area is a brushed metallic, and the screen is actually a dark transparent glass.

My (extremely basic) knowledge of this is that source 2 uses PBR shaders, but .obj is designed for traditional shaders. 
Valve seems to use the specular/gloss style for their textures, though it looks like they sometimes mislabel these gloss textures as normals. There also doesn't seem to be any specular maps, which is strange.
There doesn't seem to be any easy way from what I've gathered to convert PBR into traditional, though there seem to be a number of guides to do the opposite. However, it seems at this point that it's not possible to get correct materials information for the model when extracting it to .obj

At this point I'm at a loss in trying to get the materials to look correct compared to how they display in game, and I'm not actually sure if the formats are compatible without information I don't have and a substantial amount of work. I can cheat a bit by using the diffuse map as the specular map and manually setting the glass material, but it's just a workaround.

**Comment by k0091601** [comment]
Just wanted to point out that Robot repair models are compatible with SteamVR Home and you can just export the model and materials from the vpk and use them directly, no exporting is required., and look at how they set the controller skins via vscript in Robot repair and do the same in your map.

**Comment by Jademalo** [comment]
I'm trying to do this for core SteamVR, so when you press the home button, rather than SteamVR home since that hasn't got any custom controller support.

I am curious though - Is there anything more about doing this anywhere? I had no idea SteamVR Home was actually Source 2.

**Comment by Jademalo** [comment]
Fantastic news, I got it working in SteamVR!

It was a lot of work, I had to rescale and resize the model, split it up into it's component parts, and also fix various material errors. It works and it's textured though, so I cannot thank you enough for all the help!

https://www.dropbox.com/s/rnvwiae2hppz5jk/Robot%20Repair%20SteamVR%20Controller.zip?dl=0

I did find one more bug however - For some reason, the UVs are misaligned down by 100%. Open an exported model in blender and view the UVs in edit mode, they're underneath the actual image. This normally doesn't cause issues for most applications, but SteamVR was absolutely not happy with this.
I had to manually translate the UVs up by 100% so they aligned with the model, re-export, and then it worked perfectly.
I think this is a side effect of you fixing the upside down textures the other day, since I checked with the model I exported then and the UVs were in the right place - Just upside down.

**Comment by Marlamin** [comment]
That UV issue does sound like a side-effect of the "fix" I did. As for the texture names, we're aware and can hopefully fix that soon. For now renaming the color textures to what is referred in the mtl should be enough to get the basics working. And sadly, it'll never look as good as it does in-game due to the limitations of the OBJ format that you mentioned. Something like glTF would be better suited for this but adoption for that is still pretty low.

**Comment by Jademalo** [comment]
Alright, awesome. 
Everything seems like it's working aside from those things though, as I said I got it working in SteamVR so there's definitely enough neccesary info being exported.

Thanks again for the help and the fixes, I honestly can't thank you enough. This time last week I was pretty much ready to give up, I never expected everything to come together so quickly.

Thanks!

**Comment by AveYo** [comment]
I'm curious if  #113 improves results for this issue, too.   
I remember being phased by the green pink normal maps - that should not happen any more since dxt5nm will be accurately unpacked with all 3 coordinates.

**Comment by xPaw** [comment]
I merged our gltf work to master, and it has some basic texture exporting support now.

See #232 for further progress.
